
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Chat: 'Chat',
  ChatMember: 'ChatMember',
  ChatAdmin: 'ChatAdmin',
  Message: 'Message',
  MessageStatus: 'MessageStatus',
  Media: 'Media',
  ArchivedChat: 'ArchivedChat',
  PinnedChat: 'PinnedChat',
  MutedChat: 'MutedChat',
  Token: 'Token'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phone: 'phone',
  password: 'password',
  username: 'username',
  firstName: 'firstName',
  lastName: 'lastName',
  description: 'description',
  avatar: 'avatar',
  isPhoneVerified: 'isPhoneVerified',
  isPasswordEnabled: 'isPasswordEnabled',
  status: 'status',
  role: 'role',
  visibility: 'visibility',
  lastSeen: 'lastSeen',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ChatScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  avatar: 'avatar',
  isPrivate: 'isPrivate',
  type: 'type',
  pinnedMessageId: 'pinnedMessageId',
  lastMessageId: 'lastMessageId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdById: 'createdById'
} as const

export type ChatScalarFieldEnum = (typeof ChatScalarFieldEnum)[keyof typeof ChatScalarFieldEnum]


export const ChatMemberScalarFieldEnum = {
  id: 'id',
  joinedAt: 'joinedAt',
  role: 'role',
  chatId: 'chatId',
  userId: 'userId'
} as const

export type ChatMemberScalarFieldEnum = (typeof ChatMemberScalarFieldEnum)[keyof typeof ChatMemberScalarFieldEnum]


export const ChatAdminScalarFieldEnum = {
  id: 'id',
  addedAt: 'addedAt',
  chatId: 'chatId',
  userId: 'userId'
} as const

export type ChatAdminScalarFieldEnum = (typeof ChatAdminScalarFieldEnum)[keyof typeof ChatAdminScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  content: 'content',
  pinnedByUserId: 'pinnedByUserId',
  replyToId: 'replyToId',
  forwardedFromId: 'forwardedFromId',
  isEdited: 'isEdited',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  chatId: 'chatId',
  senderId: 'senderId'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const MessageStatusScalarFieldEnum = {
  id: 'id',
  status: 'status',
  updatedAt: 'updatedAt',
  messageId: 'messageId',
  userId: 'userId'
} as const

export type MessageStatusScalarFieldEnum = (typeof MessageStatusScalarFieldEnum)[keyof typeof MessageStatusScalarFieldEnum]


export const MediaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  type: 'type',
  url: 'url',
  fileName: 'fileName',
  fileSize: 'fileSize',
  messageId: 'messageId'
} as const

export type MediaScalarFieldEnum = (typeof MediaScalarFieldEnum)[keyof typeof MediaScalarFieldEnum]


export const ArchivedChatScalarFieldEnum = {
  id: 'id',
  archivedAt: 'archivedAt',
  userId: 'userId',
  chatId: 'chatId'
} as const

export type ArchivedChatScalarFieldEnum = (typeof ArchivedChatScalarFieldEnum)[keyof typeof ArchivedChatScalarFieldEnum]


export const PinnedChatScalarFieldEnum = {
  id: 'id',
  pinnedAt: 'pinnedAt',
  userId: 'userId',
  chatId: 'chatId'
} as const

export type PinnedChatScalarFieldEnum = (typeof PinnedChatScalarFieldEnum)[keyof typeof PinnedChatScalarFieldEnum]


export const MutedChatScalarFieldEnum = {
  id: 'id',
  mutedUntil: 'mutedUntil',
  mutedAt: 'mutedAt',
  userId: 'userId',
  chatId: 'chatId'
} as const

export type MutedChatScalarFieldEnum = (typeof MutedChatScalarFieldEnum)[keyof typeof MutedChatScalarFieldEnum]


export const TokenScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  type: 'type',
  expiresIn: 'expiresIn',
  createdAt: 'createdAt'
} as const

export type TokenScalarFieldEnum = (typeof TokenScalarFieldEnum)[keyof typeof TokenScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

