
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ArchivedChat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ArchivedChat
 * 
 */
export type ArchivedChatModel = runtime.Types.Result.DefaultSelection<Prisma.$ArchivedChatPayload>

export type AggregateArchivedChat = {
  _count: ArchivedChatCountAggregateOutputType | null
  _min: ArchivedChatMinAggregateOutputType | null
  _max: ArchivedChatMaxAggregateOutputType | null
}

export type ArchivedChatMinAggregateOutputType = {
  id: string | null
  archivedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type ArchivedChatMaxAggregateOutputType = {
  id: string | null
  archivedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type ArchivedChatCountAggregateOutputType = {
  id: number
  archivedAt: number
  userId: number
  chatId: number
  _all: number
}


export type ArchivedChatMinAggregateInputType = {
  id?: true
  archivedAt?: true
  userId?: true
  chatId?: true
}

export type ArchivedChatMaxAggregateInputType = {
  id?: true
  archivedAt?: true
  userId?: true
  chatId?: true
}

export type ArchivedChatCountAggregateInputType = {
  id?: true
  archivedAt?: true
  userId?: true
  chatId?: true
  _all?: true
}

export type ArchivedChatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArchivedChat to aggregate.
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArchivedChats to fetch.
   */
  orderBy?: Prisma.ArchivedChatOrderByWithRelationInput | Prisma.ArchivedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ArchivedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArchivedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArchivedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ArchivedChats
  **/
  _count?: true | ArchivedChatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ArchivedChatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ArchivedChatMaxAggregateInputType
}

export type GetArchivedChatAggregateType<T extends ArchivedChatAggregateArgs> = {
      [P in keyof T & keyof AggregateArchivedChat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateArchivedChat[P]>
    : Prisma.GetScalarType<T[P], AggregateArchivedChat[P]>
}




export type ArchivedChatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArchivedChatWhereInput
  orderBy?: Prisma.ArchivedChatOrderByWithAggregationInput | Prisma.ArchivedChatOrderByWithAggregationInput[]
  by: Prisma.ArchivedChatScalarFieldEnum[] | Prisma.ArchivedChatScalarFieldEnum
  having?: Prisma.ArchivedChatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ArchivedChatCountAggregateInputType | true
  _min?: ArchivedChatMinAggregateInputType
  _max?: ArchivedChatMaxAggregateInputType
}

export type ArchivedChatGroupByOutputType = {
  id: string
  archivedAt: Date
  userId: string
  chatId: string
  _count: ArchivedChatCountAggregateOutputType | null
  _min: ArchivedChatMinAggregateOutputType | null
  _max: ArchivedChatMaxAggregateOutputType | null
}

type GetArchivedChatGroupByPayload<T extends ArchivedChatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ArchivedChatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ArchivedChatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ArchivedChatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ArchivedChatGroupByOutputType[P]>
      }
    >
  >



export type ArchivedChatWhereInput = {
  AND?: Prisma.ArchivedChatWhereInput | Prisma.ArchivedChatWhereInput[]
  OR?: Prisma.ArchivedChatWhereInput[]
  NOT?: Prisma.ArchivedChatWhereInput | Prisma.ArchivedChatWhereInput[]
  id?: Prisma.StringFilter<"ArchivedChat"> | string
  archivedAt?: Prisma.DateTimeFilter<"ArchivedChat"> | Date | string
  userId?: Prisma.StringFilter<"ArchivedChat"> | string
  chatId?: Prisma.StringFilter<"ArchivedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}

export type ArchivedChatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  chat?: Prisma.ChatOrderByWithRelationInput
}

export type ArchivedChatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_chatId?: Prisma.ArchivedChatUserIdChatIdCompoundUniqueInput
  AND?: Prisma.ArchivedChatWhereInput | Prisma.ArchivedChatWhereInput[]
  OR?: Prisma.ArchivedChatWhereInput[]
  NOT?: Prisma.ArchivedChatWhereInput | Prisma.ArchivedChatWhereInput[]
  archivedAt?: Prisma.DateTimeFilter<"ArchivedChat"> | Date | string
  userId?: Prisma.StringFilter<"ArchivedChat"> | string
  chatId?: Prisma.StringFilter<"ArchivedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}, "id" | "userId_chatId">

export type ArchivedChatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  _count?: Prisma.ArchivedChatCountOrderByAggregateInput
  _max?: Prisma.ArchivedChatMaxOrderByAggregateInput
  _min?: Prisma.ArchivedChatMinOrderByAggregateInput
}

export type ArchivedChatScalarWhereWithAggregatesInput = {
  AND?: Prisma.ArchivedChatScalarWhereWithAggregatesInput | Prisma.ArchivedChatScalarWhereWithAggregatesInput[]
  OR?: Prisma.ArchivedChatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ArchivedChatScalarWhereWithAggregatesInput | Prisma.ArchivedChatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ArchivedChat"> | string
  archivedAt?: Prisma.DateTimeWithAggregatesFilter<"ArchivedChat"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"ArchivedChat"> | string
  chatId?: Prisma.StringWithAggregatesFilter<"ArchivedChat"> | string
}

export type ArchivedChatCreateInput = {
  id?: string
  archivedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutArchivedChatsInput
  chat: Prisma.ChatCreateNestedOneWithoutArchivedByInput
}

export type ArchivedChatUncheckedCreateInput = {
  id?: string
  archivedAt?: Date | string
  userId: string
  chatId: string
}

export type ArchivedChatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutArchivedChatsNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutArchivedByNestedInput
}

export type ArchivedChatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArchivedChatCreateManyInput = {
  id?: string
  archivedAt?: Date | string
  userId: string
  chatId: string
}

export type ArchivedChatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivedChatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArchivedChatListRelationFilter = {
  every?: Prisma.ArchivedChatWhereInput
  some?: Prisma.ArchivedChatWhereInput
  none?: Prisma.ArchivedChatWhereInput
}

export type ArchivedChatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ArchivedChatUserIdChatIdCompoundUniqueInput = {
  userId: string
  chatId: string
}

export type ArchivedChatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type ArchivedChatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type ArchivedChatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type ArchivedChatCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput> | Prisma.ArchivedChatCreateWithoutUserInput[] | Prisma.ArchivedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutUserInput | Prisma.ArchivedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ArchivedChatCreateManyUserInputEnvelope
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
}

export type ArchivedChatUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput> | Prisma.ArchivedChatCreateWithoutUserInput[] | Prisma.ArchivedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutUserInput | Prisma.ArchivedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ArchivedChatCreateManyUserInputEnvelope
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
}

export type ArchivedChatUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput> | Prisma.ArchivedChatCreateWithoutUserInput[] | Prisma.ArchivedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutUserInput | Prisma.ArchivedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ArchivedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.ArchivedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ArchivedChatCreateManyUserInputEnvelope
  set?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  disconnect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  delete?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  update?: Prisma.ArchivedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.ArchivedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ArchivedChatUpdateManyWithWhereWithoutUserInput | Prisma.ArchivedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
}

export type ArchivedChatUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput> | Prisma.ArchivedChatCreateWithoutUserInput[] | Prisma.ArchivedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutUserInput | Prisma.ArchivedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ArchivedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.ArchivedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ArchivedChatCreateManyUserInputEnvelope
  set?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  disconnect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  delete?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  update?: Prisma.ArchivedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.ArchivedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ArchivedChatUpdateManyWithWhereWithoutUserInput | Prisma.ArchivedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
}

export type ArchivedChatCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput> | Prisma.ArchivedChatCreateWithoutChatInput[] | Prisma.ArchivedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutChatInput | Prisma.ArchivedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.ArchivedChatCreateManyChatInputEnvelope
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
}

export type ArchivedChatUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput> | Prisma.ArchivedChatCreateWithoutChatInput[] | Prisma.ArchivedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutChatInput | Prisma.ArchivedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.ArchivedChatCreateManyChatInputEnvelope
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
}

export type ArchivedChatUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput> | Prisma.ArchivedChatCreateWithoutChatInput[] | Prisma.ArchivedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutChatInput | Prisma.ArchivedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.ArchivedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.ArchivedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.ArchivedChatCreateManyChatInputEnvelope
  set?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  disconnect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  delete?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  update?: Prisma.ArchivedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.ArchivedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.ArchivedChatUpdateManyWithWhereWithoutChatInput | Prisma.ArchivedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
}

export type ArchivedChatUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput> | Prisma.ArchivedChatCreateWithoutChatInput[] | Prisma.ArchivedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ArchivedChatCreateOrConnectWithoutChatInput | Prisma.ArchivedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.ArchivedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.ArchivedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.ArchivedChatCreateManyChatInputEnvelope
  set?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  disconnect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  delete?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  connect?: Prisma.ArchivedChatWhereUniqueInput | Prisma.ArchivedChatWhereUniqueInput[]
  update?: Prisma.ArchivedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.ArchivedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.ArchivedChatUpdateManyWithWhereWithoutChatInput | Prisma.ArchivedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
}

export type ArchivedChatCreateWithoutUserInput = {
  id?: string
  archivedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutArchivedByInput
}

export type ArchivedChatUncheckedCreateWithoutUserInput = {
  id?: string
  archivedAt?: Date | string
  chatId: string
}

export type ArchivedChatCreateOrConnectWithoutUserInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput>
}

export type ArchivedChatCreateManyUserInputEnvelope = {
  data: Prisma.ArchivedChatCreateManyUserInput | Prisma.ArchivedChatCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ArchivedChatUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.ArchivedChatUpdateWithoutUserInput, Prisma.ArchivedChatUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ArchivedChatCreateWithoutUserInput, Prisma.ArchivedChatUncheckedCreateWithoutUserInput>
}

export type ArchivedChatUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.ArchivedChatUpdateWithoutUserInput, Prisma.ArchivedChatUncheckedUpdateWithoutUserInput>
}

export type ArchivedChatUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ArchivedChatScalarWhereInput
  data: Prisma.XOR<Prisma.ArchivedChatUpdateManyMutationInput, Prisma.ArchivedChatUncheckedUpdateManyWithoutUserInput>
}

export type ArchivedChatScalarWhereInput = {
  AND?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
  OR?: Prisma.ArchivedChatScalarWhereInput[]
  NOT?: Prisma.ArchivedChatScalarWhereInput | Prisma.ArchivedChatScalarWhereInput[]
  id?: Prisma.StringFilter<"ArchivedChat"> | string
  archivedAt?: Prisma.DateTimeFilter<"ArchivedChat"> | Date | string
  userId?: Prisma.StringFilter<"ArchivedChat"> | string
  chatId?: Prisma.StringFilter<"ArchivedChat"> | string
}

export type ArchivedChatCreateWithoutChatInput = {
  id?: string
  archivedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutArchivedChatsInput
}

export type ArchivedChatUncheckedCreateWithoutChatInput = {
  id?: string
  archivedAt?: Date | string
  userId: string
}

export type ArchivedChatCreateOrConnectWithoutChatInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput>
}

export type ArchivedChatCreateManyChatInputEnvelope = {
  data: Prisma.ArchivedChatCreateManyChatInput | Prisma.ArchivedChatCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type ArchivedChatUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.ArchivedChatUpdateWithoutChatInput, Prisma.ArchivedChatUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.ArchivedChatCreateWithoutChatInput, Prisma.ArchivedChatUncheckedCreateWithoutChatInput>
}

export type ArchivedChatUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.ArchivedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.ArchivedChatUpdateWithoutChatInput, Prisma.ArchivedChatUncheckedUpdateWithoutChatInput>
}

export type ArchivedChatUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.ArchivedChatScalarWhereInput
  data: Prisma.XOR<Prisma.ArchivedChatUpdateManyMutationInput, Prisma.ArchivedChatUncheckedUpdateManyWithoutChatInput>
}

export type ArchivedChatCreateManyUserInput = {
  id?: string
  archivedAt?: Date | string
  chatId: string
}

export type ArchivedChatUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutArchivedByNestedInput
}

export type ArchivedChatUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArchivedChatUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArchivedChatCreateManyChatInput = {
  id?: string
  archivedAt?: Date | string
  userId: string
}

export type ArchivedChatUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutArchivedChatsNestedInput
}

export type ArchivedChatUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArchivedChatUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ArchivedChatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  archivedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivedChat"]>

export type ArchivedChatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  archivedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivedChat"]>

export type ArchivedChatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  archivedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivedChat"]>

export type ArchivedChatSelectScalar = {
  id?: boolean
  archivedAt?: boolean
  userId?: boolean
  chatId?: boolean
}

export type ArchivedChatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "archivedAt" | "userId" | "chatId", ExtArgs["result"]["archivedChat"]>
export type ArchivedChatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type ArchivedChatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type ArchivedChatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}

export type $ArchivedChatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ArchivedChat"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    chat: Prisma.$ChatPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    archivedAt: Date
    userId: string
    chatId: string
  }, ExtArgs["result"]["archivedChat"]>
  composites: {}
}

export type ArchivedChatGetPayload<S extends boolean | null | undefined | ArchivedChatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload, S>

export type ArchivedChatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ArchivedChatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ArchivedChatCountAggregateInputType | true
  }

export interface ArchivedChatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ArchivedChat'], meta: { name: 'ArchivedChat' } }
  /**
   * Find zero or one ArchivedChat that matches the filter.
   * @param {ArchivedChatFindUniqueArgs} args - Arguments to find a ArchivedChat
   * @example
   * // Get one ArchivedChat
   * const archivedChat = await prisma.archivedChat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ArchivedChatFindUniqueArgs>(args: Prisma.SelectSubset<T, ArchivedChatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ArchivedChat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ArchivedChatFindUniqueOrThrowArgs} args - Arguments to find a ArchivedChat
   * @example
   * // Get one ArchivedChat
   * const archivedChat = await prisma.archivedChat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ArchivedChatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ArchivedChatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArchivedChat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatFindFirstArgs} args - Arguments to find a ArchivedChat
   * @example
   * // Get one ArchivedChat
   * const archivedChat = await prisma.archivedChat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ArchivedChatFindFirstArgs>(args?: Prisma.SelectSubset<T, ArchivedChatFindFirstArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArchivedChat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatFindFirstOrThrowArgs} args - Arguments to find a ArchivedChat
   * @example
   * // Get one ArchivedChat
   * const archivedChat = await prisma.archivedChat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ArchivedChatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ArchivedChatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ArchivedChats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ArchivedChats
   * const archivedChats = await prisma.archivedChat.findMany()
   * 
   * // Get first 10 ArchivedChats
   * const archivedChats = await prisma.archivedChat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const archivedChatWithIdOnly = await prisma.archivedChat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ArchivedChatFindManyArgs>(args?: Prisma.SelectSubset<T, ArchivedChatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ArchivedChat.
   * @param {ArchivedChatCreateArgs} args - Arguments to create a ArchivedChat.
   * @example
   * // Create one ArchivedChat
   * const ArchivedChat = await prisma.archivedChat.create({
   *   data: {
   *     // ... data to create a ArchivedChat
   *   }
   * })
   * 
   */
  create<T extends ArchivedChatCreateArgs>(args: Prisma.SelectSubset<T, ArchivedChatCreateArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ArchivedChats.
   * @param {ArchivedChatCreateManyArgs} args - Arguments to create many ArchivedChats.
   * @example
   * // Create many ArchivedChats
   * const archivedChat = await prisma.archivedChat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ArchivedChatCreateManyArgs>(args?: Prisma.SelectSubset<T, ArchivedChatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ArchivedChats and returns the data saved in the database.
   * @param {ArchivedChatCreateManyAndReturnArgs} args - Arguments to create many ArchivedChats.
   * @example
   * // Create many ArchivedChats
   * const archivedChat = await prisma.archivedChat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ArchivedChats and only return the `id`
   * const archivedChatWithIdOnly = await prisma.archivedChat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ArchivedChatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ArchivedChatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ArchivedChat.
   * @param {ArchivedChatDeleteArgs} args - Arguments to delete one ArchivedChat.
   * @example
   * // Delete one ArchivedChat
   * const ArchivedChat = await prisma.archivedChat.delete({
   *   where: {
   *     // ... filter to delete one ArchivedChat
   *   }
   * })
   * 
   */
  delete<T extends ArchivedChatDeleteArgs>(args: Prisma.SelectSubset<T, ArchivedChatDeleteArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ArchivedChat.
   * @param {ArchivedChatUpdateArgs} args - Arguments to update one ArchivedChat.
   * @example
   * // Update one ArchivedChat
   * const archivedChat = await prisma.archivedChat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ArchivedChatUpdateArgs>(args: Prisma.SelectSubset<T, ArchivedChatUpdateArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ArchivedChats.
   * @param {ArchivedChatDeleteManyArgs} args - Arguments to filter ArchivedChats to delete.
   * @example
   * // Delete a few ArchivedChats
   * const { count } = await prisma.archivedChat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ArchivedChatDeleteManyArgs>(args?: Prisma.SelectSubset<T, ArchivedChatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArchivedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ArchivedChats
   * const archivedChat = await prisma.archivedChat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ArchivedChatUpdateManyArgs>(args: Prisma.SelectSubset<T, ArchivedChatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArchivedChats and returns the data updated in the database.
   * @param {ArchivedChatUpdateManyAndReturnArgs} args - Arguments to update many ArchivedChats.
   * @example
   * // Update many ArchivedChats
   * const archivedChat = await prisma.archivedChat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ArchivedChats and only return the `id`
   * const archivedChatWithIdOnly = await prisma.archivedChat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ArchivedChatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ArchivedChatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ArchivedChat.
   * @param {ArchivedChatUpsertArgs} args - Arguments to update or create a ArchivedChat.
   * @example
   * // Update or create a ArchivedChat
   * const archivedChat = await prisma.archivedChat.upsert({
   *   create: {
   *     // ... data to create a ArchivedChat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ArchivedChat we want to update
   *   }
   * })
   */
  upsert<T extends ArchivedChatUpsertArgs>(args: Prisma.SelectSubset<T, ArchivedChatUpsertArgs<ExtArgs>>): Prisma.Prisma__ArchivedChatClient<runtime.Types.Result.GetResult<Prisma.$ArchivedChatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ArchivedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatCountArgs} args - Arguments to filter ArchivedChats to count.
   * @example
   * // Count the number of ArchivedChats
   * const count = await prisma.archivedChat.count({
   *   where: {
   *     // ... the filter for the ArchivedChats we want to count
   *   }
   * })
  **/
  count<T extends ArchivedChatCountArgs>(
    args?: Prisma.Subset<T, ArchivedChatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ArchivedChatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ArchivedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ArchivedChatAggregateArgs>(args: Prisma.Subset<T, ArchivedChatAggregateArgs>): Prisma.PrismaPromise<GetArchivedChatAggregateType<T>>

  /**
   * Group by ArchivedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivedChatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ArchivedChatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ArchivedChatGroupByArgs['orderBy'] }
      : { orderBy?: ArchivedChatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ArchivedChatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetArchivedChatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ArchivedChat model
 */
readonly fields: ArchivedChatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ArchivedChat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ArchivedChatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ArchivedChat model
 */
export interface ArchivedChatFieldRefs {
  readonly id: Prisma.FieldRef<"ArchivedChat", 'String'>
  readonly archivedAt: Prisma.FieldRef<"ArchivedChat", 'DateTime'>
  readonly userId: Prisma.FieldRef<"ArchivedChat", 'String'>
  readonly chatId: Prisma.FieldRef<"ArchivedChat", 'String'>
}
    

// Custom InputTypes
/**
 * ArchivedChat findUnique
 */
export type ArchivedChatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter, which ArchivedChat to fetch.
   */
  where: Prisma.ArchivedChatWhereUniqueInput
}

/**
 * ArchivedChat findUniqueOrThrow
 */
export type ArchivedChatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter, which ArchivedChat to fetch.
   */
  where: Prisma.ArchivedChatWhereUniqueInput
}

/**
 * ArchivedChat findFirst
 */
export type ArchivedChatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter, which ArchivedChat to fetch.
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArchivedChats to fetch.
   */
  orderBy?: Prisma.ArchivedChatOrderByWithRelationInput | Prisma.ArchivedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArchivedChats.
   */
  cursor?: Prisma.ArchivedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArchivedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArchivedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArchivedChats.
   */
  distinct?: Prisma.ArchivedChatScalarFieldEnum | Prisma.ArchivedChatScalarFieldEnum[]
}

/**
 * ArchivedChat findFirstOrThrow
 */
export type ArchivedChatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter, which ArchivedChat to fetch.
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArchivedChats to fetch.
   */
  orderBy?: Prisma.ArchivedChatOrderByWithRelationInput | Prisma.ArchivedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArchivedChats.
   */
  cursor?: Prisma.ArchivedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArchivedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArchivedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArchivedChats.
   */
  distinct?: Prisma.ArchivedChatScalarFieldEnum | Prisma.ArchivedChatScalarFieldEnum[]
}

/**
 * ArchivedChat findMany
 */
export type ArchivedChatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter, which ArchivedChats to fetch.
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArchivedChats to fetch.
   */
  orderBy?: Prisma.ArchivedChatOrderByWithRelationInput | Prisma.ArchivedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ArchivedChats.
   */
  cursor?: Prisma.ArchivedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArchivedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArchivedChats.
   */
  skip?: number
  distinct?: Prisma.ArchivedChatScalarFieldEnum | Prisma.ArchivedChatScalarFieldEnum[]
}

/**
 * ArchivedChat create
 */
export type ArchivedChatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * The data needed to create a ArchivedChat.
   */
  data: Prisma.XOR<Prisma.ArchivedChatCreateInput, Prisma.ArchivedChatUncheckedCreateInput>
}

/**
 * ArchivedChat createMany
 */
export type ArchivedChatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ArchivedChats.
   */
  data: Prisma.ArchivedChatCreateManyInput | Prisma.ArchivedChatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ArchivedChat createManyAndReturn
 */
export type ArchivedChatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * The data used to create many ArchivedChats.
   */
  data: Prisma.ArchivedChatCreateManyInput | Prisma.ArchivedChatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ArchivedChat update
 */
export type ArchivedChatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * The data needed to update a ArchivedChat.
   */
  data: Prisma.XOR<Prisma.ArchivedChatUpdateInput, Prisma.ArchivedChatUncheckedUpdateInput>
  /**
   * Choose, which ArchivedChat to update.
   */
  where: Prisma.ArchivedChatWhereUniqueInput
}

/**
 * ArchivedChat updateMany
 */
export type ArchivedChatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ArchivedChats.
   */
  data: Prisma.XOR<Prisma.ArchivedChatUpdateManyMutationInput, Prisma.ArchivedChatUncheckedUpdateManyInput>
  /**
   * Filter which ArchivedChats to update
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * Limit how many ArchivedChats to update.
   */
  limit?: number
}

/**
 * ArchivedChat updateManyAndReturn
 */
export type ArchivedChatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * The data used to update ArchivedChats.
   */
  data: Prisma.XOR<Prisma.ArchivedChatUpdateManyMutationInput, Prisma.ArchivedChatUncheckedUpdateManyInput>
  /**
   * Filter which ArchivedChats to update
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * Limit how many ArchivedChats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ArchivedChat upsert
 */
export type ArchivedChatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * The filter to search for the ArchivedChat to update in case it exists.
   */
  where: Prisma.ArchivedChatWhereUniqueInput
  /**
   * In case the ArchivedChat found by the `where` argument doesn't exist, create a new ArchivedChat with this data.
   */
  create: Prisma.XOR<Prisma.ArchivedChatCreateInput, Prisma.ArchivedChatUncheckedCreateInput>
  /**
   * In case the ArchivedChat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ArchivedChatUpdateInput, Prisma.ArchivedChatUncheckedUpdateInput>
}

/**
 * ArchivedChat delete
 */
export type ArchivedChatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
  /**
   * Filter which ArchivedChat to delete.
   */
  where: Prisma.ArchivedChatWhereUniqueInput
}

/**
 * ArchivedChat deleteMany
 */
export type ArchivedChatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArchivedChats to delete
   */
  where?: Prisma.ArchivedChatWhereInput
  /**
   * Limit how many ArchivedChats to delete.
   */
  limit?: number
}

/**
 * ArchivedChat without action
 */
export type ArchivedChatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArchivedChat
   */
  select?: Prisma.ArchivedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArchivedChat
   */
  omit?: Prisma.ArchivedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivedChatInclude<ExtArgs> | null
}
