
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ChatAdmin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ChatAdmin
 * 
 */
export type ChatAdminModel = runtime.Types.Result.DefaultSelection<Prisma.$ChatAdminPayload>

export type AggregateChatAdmin = {
  _count: ChatAdminCountAggregateOutputType | null
  _min: ChatAdminMinAggregateOutputType | null
  _max: ChatAdminMaxAggregateOutputType | null
}

export type ChatAdminMinAggregateOutputType = {
  id: string | null
  addedAt: Date | null
  chatId: string | null
  userId: string | null
}

export type ChatAdminMaxAggregateOutputType = {
  id: string | null
  addedAt: Date | null
  chatId: string | null
  userId: string | null
}

export type ChatAdminCountAggregateOutputType = {
  id: number
  addedAt: number
  chatId: number
  userId: number
  _all: number
}


export type ChatAdminMinAggregateInputType = {
  id?: true
  addedAt?: true
  chatId?: true
  userId?: true
}

export type ChatAdminMaxAggregateInputType = {
  id?: true
  addedAt?: true
  chatId?: true
  userId?: true
}

export type ChatAdminCountAggregateInputType = {
  id?: true
  addedAt?: true
  chatId?: true
  userId?: true
  _all?: true
}

export type ChatAdminAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChatAdmin to aggregate.
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatAdmins to fetch.
   */
  orderBy?: Prisma.ChatAdminOrderByWithRelationInput | Prisma.ChatAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChatAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ChatAdmins
  **/
  _count?: true | ChatAdminCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChatAdminMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChatAdminMaxAggregateInputType
}

export type GetChatAdminAggregateType<T extends ChatAdminAggregateArgs> = {
      [P in keyof T & keyof AggregateChatAdmin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChatAdmin[P]>
    : Prisma.GetScalarType<T[P], AggregateChatAdmin[P]>
}




export type ChatAdminGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatAdminWhereInput
  orderBy?: Prisma.ChatAdminOrderByWithAggregationInput | Prisma.ChatAdminOrderByWithAggregationInput[]
  by: Prisma.ChatAdminScalarFieldEnum[] | Prisma.ChatAdminScalarFieldEnum
  having?: Prisma.ChatAdminScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChatAdminCountAggregateInputType | true
  _min?: ChatAdminMinAggregateInputType
  _max?: ChatAdminMaxAggregateInputType
}

export type ChatAdminGroupByOutputType = {
  id: string
  addedAt: Date
  chatId: string
  userId: string
  _count: ChatAdminCountAggregateOutputType | null
  _min: ChatAdminMinAggregateOutputType | null
  _max: ChatAdminMaxAggregateOutputType | null
}

type GetChatAdminGroupByPayload<T extends ChatAdminGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChatAdminGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChatAdminGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChatAdminGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChatAdminGroupByOutputType[P]>
      }
    >
  >



export type ChatAdminWhereInput = {
  AND?: Prisma.ChatAdminWhereInput | Prisma.ChatAdminWhereInput[]
  OR?: Prisma.ChatAdminWhereInput[]
  NOT?: Prisma.ChatAdminWhereInput | Prisma.ChatAdminWhereInput[]
  id?: Prisma.StringFilter<"ChatAdmin"> | string
  addedAt?: Prisma.DateTimeFilter<"ChatAdmin"> | Date | string
  chatId?: Prisma.StringFilter<"ChatAdmin"> | string
  userId?: Prisma.StringFilter<"ChatAdmin"> | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ChatAdminOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chat?: Prisma.ChatOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ChatAdminWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  chatId_userId?: Prisma.ChatAdminChatIdUserIdCompoundUniqueInput
  AND?: Prisma.ChatAdminWhereInput | Prisma.ChatAdminWhereInput[]
  OR?: Prisma.ChatAdminWhereInput[]
  NOT?: Prisma.ChatAdminWhereInput | Prisma.ChatAdminWhereInput[]
  addedAt?: Prisma.DateTimeFilter<"ChatAdmin"> | Date | string
  chatId?: Prisma.StringFilter<"ChatAdmin"> | string
  userId?: Prisma.StringFilter<"ChatAdmin"> | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "chatId_userId">

export type ChatAdminOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.ChatAdminCountOrderByAggregateInput
  _max?: Prisma.ChatAdminMaxOrderByAggregateInput
  _min?: Prisma.ChatAdminMinOrderByAggregateInput
}

export type ChatAdminScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChatAdminScalarWhereWithAggregatesInput | Prisma.ChatAdminScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChatAdminScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChatAdminScalarWhereWithAggregatesInput | Prisma.ChatAdminScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ChatAdmin"> | string
  addedAt?: Prisma.DateTimeWithAggregatesFilter<"ChatAdmin"> | Date | string
  chatId?: Prisma.StringWithAggregatesFilter<"ChatAdmin"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ChatAdmin"> | string
}

export type ChatAdminCreateInput = {
  id?: string
  addedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutAdminsInput
  user: Prisma.UserCreateNestedOneWithoutChatAdminsInput
}

export type ChatAdminUncheckedCreateInput = {
  id?: string
  addedAt?: Date | string
  chatId: string
  userId: string
}

export type ChatAdminUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutAdminsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutChatAdminsNestedInput
}

export type ChatAdminUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatAdminCreateManyInput = {
  id?: string
  addedAt?: Date | string
  chatId: string
  userId: string
}

export type ChatAdminUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatAdminUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatAdminListRelationFilter = {
  every?: Prisma.ChatAdminWhereInput
  some?: Prisma.ChatAdminWhereInput
  none?: Prisma.ChatAdminWhereInput
}

export type ChatAdminOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChatAdminChatIdUserIdCompoundUniqueInput = {
  chatId: string
  userId: string
}

export type ChatAdminCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ChatAdminMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ChatAdminMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ChatAdminCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput> | Prisma.ChatAdminCreateWithoutUserInput[] | Prisma.ChatAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutUserInput | Prisma.ChatAdminCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ChatAdminCreateManyUserInputEnvelope
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
}

export type ChatAdminUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput> | Prisma.ChatAdminCreateWithoutUserInput[] | Prisma.ChatAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutUserInput | Prisma.ChatAdminCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ChatAdminCreateManyUserInputEnvelope
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
}

export type ChatAdminUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput> | Prisma.ChatAdminCreateWithoutUserInput[] | Prisma.ChatAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutUserInput | Prisma.ChatAdminCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ChatAdminUpsertWithWhereUniqueWithoutUserInput | Prisma.ChatAdminUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ChatAdminCreateManyUserInputEnvelope
  set?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  disconnect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  delete?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  update?: Prisma.ChatAdminUpdateWithWhereUniqueWithoutUserInput | Prisma.ChatAdminUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ChatAdminUpdateManyWithWhereWithoutUserInput | Prisma.ChatAdminUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
}

export type ChatAdminUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput> | Prisma.ChatAdminCreateWithoutUserInput[] | Prisma.ChatAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutUserInput | Prisma.ChatAdminCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ChatAdminUpsertWithWhereUniqueWithoutUserInput | Prisma.ChatAdminUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ChatAdminCreateManyUserInputEnvelope
  set?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  disconnect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  delete?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  update?: Prisma.ChatAdminUpdateWithWhereUniqueWithoutUserInput | Prisma.ChatAdminUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ChatAdminUpdateManyWithWhereWithoutUserInput | Prisma.ChatAdminUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
}

export type ChatAdminCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput> | Prisma.ChatAdminCreateWithoutChatInput[] | Prisma.ChatAdminUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutChatInput | Prisma.ChatAdminCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.ChatAdminCreateManyChatInputEnvelope
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
}

export type ChatAdminUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput> | Prisma.ChatAdminCreateWithoutChatInput[] | Prisma.ChatAdminUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutChatInput | Prisma.ChatAdminCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.ChatAdminCreateManyChatInputEnvelope
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
}

export type ChatAdminUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput> | Prisma.ChatAdminCreateWithoutChatInput[] | Prisma.ChatAdminUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutChatInput | Prisma.ChatAdminCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.ChatAdminUpsertWithWhereUniqueWithoutChatInput | Prisma.ChatAdminUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.ChatAdminCreateManyChatInputEnvelope
  set?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  disconnect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  delete?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  update?: Prisma.ChatAdminUpdateWithWhereUniqueWithoutChatInput | Prisma.ChatAdminUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.ChatAdminUpdateManyWithWhereWithoutChatInput | Prisma.ChatAdminUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
}

export type ChatAdminUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput> | Prisma.ChatAdminCreateWithoutChatInput[] | Prisma.ChatAdminUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.ChatAdminCreateOrConnectWithoutChatInput | Prisma.ChatAdminCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.ChatAdminUpsertWithWhereUniqueWithoutChatInput | Prisma.ChatAdminUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.ChatAdminCreateManyChatInputEnvelope
  set?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  disconnect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  delete?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  connect?: Prisma.ChatAdminWhereUniqueInput | Prisma.ChatAdminWhereUniqueInput[]
  update?: Prisma.ChatAdminUpdateWithWhereUniqueWithoutChatInput | Prisma.ChatAdminUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.ChatAdminUpdateManyWithWhereWithoutChatInput | Prisma.ChatAdminUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
}

export type ChatAdminCreateWithoutUserInput = {
  id?: string
  addedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutAdminsInput
}

export type ChatAdminUncheckedCreateWithoutUserInput = {
  id?: string
  addedAt?: Date | string
  chatId: string
}

export type ChatAdminCreateOrConnectWithoutUserInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput>
}

export type ChatAdminCreateManyUserInputEnvelope = {
  data: Prisma.ChatAdminCreateManyUserInput | Prisma.ChatAdminCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ChatAdminUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatAdminUpdateWithoutUserInput, Prisma.ChatAdminUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ChatAdminCreateWithoutUserInput, Prisma.ChatAdminUncheckedCreateWithoutUserInput>
}

export type ChatAdminUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatAdminUpdateWithoutUserInput, Prisma.ChatAdminUncheckedUpdateWithoutUserInput>
}

export type ChatAdminUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ChatAdminScalarWhereInput
  data: Prisma.XOR<Prisma.ChatAdminUpdateManyMutationInput, Prisma.ChatAdminUncheckedUpdateManyWithoutUserInput>
}

export type ChatAdminScalarWhereInput = {
  AND?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
  OR?: Prisma.ChatAdminScalarWhereInput[]
  NOT?: Prisma.ChatAdminScalarWhereInput | Prisma.ChatAdminScalarWhereInput[]
  id?: Prisma.StringFilter<"ChatAdmin"> | string
  addedAt?: Prisma.DateTimeFilter<"ChatAdmin"> | Date | string
  chatId?: Prisma.StringFilter<"ChatAdmin"> | string
  userId?: Prisma.StringFilter<"ChatAdmin"> | string
}

export type ChatAdminCreateWithoutChatInput = {
  id?: string
  addedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutChatAdminsInput
}

export type ChatAdminUncheckedCreateWithoutChatInput = {
  id?: string
  addedAt?: Date | string
  userId: string
}

export type ChatAdminCreateOrConnectWithoutChatInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput>
}

export type ChatAdminCreateManyChatInputEnvelope = {
  data: Prisma.ChatAdminCreateManyChatInput | Prisma.ChatAdminCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type ChatAdminUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatAdminUpdateWithoutChatInput, Prisma.ChatAdminUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.ChatAdminCreateWithoutChatInput, Prisma.ChatAdminUncheckedCreateWithoutChatInput>
}

export type ChatAdminUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.ChatAdminWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatAdminUpdateWithoutChatInput, Prisma.ChatAdminUncheckedUpdateWithoutChatInput>
}

export type ChatAdminUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.ChatAdminScalarWhereInput
  data: Prisma.XOR<Prisma.ChatAdminUpdateManyMutationInput, Prisma.ChatAdminUncheckedUpdateManyWithoutChatInput>
}

export type ChatAdminCreateManyUserInput = {
  id?: string
  addedAt?: Date | string
  chatId: string
}

export type ChatAdminUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutAdminsNestedInput
}

export type ChatAdminUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatAdminUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatAdminCreateManyChatInput = {
  id?: string
  addedAt?: Date | string
  userId: string
}

export type ChatAdminUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutChatAdminsNestedInput
}

export type ChatAdminUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatAdminUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ChatAdminSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  addedAt?: boolean
  chatId?: boolean
  userId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chatAdmin"]>

export type ChatAdminSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  addedAt?: boolean
  chatId?: boolean
  userId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chatAdmin"]>

export type ChatAdminSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  addedAt?: boolean
  chatId?: boolean
  userId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chatAdmin"]>

export type ChatAdminSelectScalar = {
  id?: boolean
  addedAt?: boolean
  chatId?: boolean
  userId?: boolean
}

export type ChatAdminOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "addedAt" | "chatId" | "userId", ExtArgs["result"]["chatAdmin"]>
export type ChatAdminInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ChatAdminIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ChatAdminIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ChatAdminPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ChatAdmin"
  objects: {
    chat: Prisma.$ChatPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    addedAt: Date
    chatId: string
    userId: string
  }, ExtArgs["result"]["chatAdmin"]>
  composites: {}
}

export type ChatAdminGetPayload<S extends boolean | null | undefined | ChatAdminDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload, S>

export type ChatAdminCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChatAdminFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChatAdminCountAggregateInputType | true
  }

export interface ChatAdminDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ChatAdmin'], meta: { name: 'ChatAdmin' } }
  /**
   * Find zero or one ChatAdmin that matches the filter.
   * @param {ChatAdminFindUniqueArgs} args - Arguments to find a ChatAdmin
   * @example
   * // Get one ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChatAdminFindUniqueArgs>(args: Prisma.SelectSubset<T, ChatAdminFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ChatAdmin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChatAdminFindUniqueOrThrowArgs} args - Arguments to find a ChatAdmin
   * @example
   * // Get one ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChatAdminFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChatAdminFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChatAdmin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminFindFirstArgs} args - Arguments to find a ChatAdmin
   * @example
   * // Get one ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChatAdminFindFirstArgs>(args?: Prisma.SelectSubset<T, ChatAdminFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChatAdmin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminFindFirstOrThrowArgs} args - Arguments to find a ChatAdmin
   * @example
   * // Get one ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChatAdminFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChatAdminFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ChatAdmins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ChatAdmins
   * const chatAdmins = await prisma.chatAdmin.findMany()
   * 
   * // Get first 10 ChatAdmins
   * const chatAdmins = await prisma.chatAdmin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const chatAdminWithIdOnly = await prisma.chatAdmin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChatAdminFindManyArgs>(args?: Prisma.SelectSubset<T, ChatAdminFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ChatAdmin.
   * @param {ChatAdminCreateArgs} args - Arguments to create a ChatAdmin.
   * @example
   * // Create one ChatAdmin
   * const ChatAdmin = await prisma.chatAdmin.create({
   *   data: {
   *     // ... data to create a ChatAdmin
   *   }
   * })
   * 
   */
  create<T extends ChatAdminCreateArgs>(args: Prisma.SelectSubset<T, ChatAdminCreateArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ChatAdmins.
   * @param {ChatAdminCreateManyArgs} args - Arguments to create many ChatAdmins.
   * @example
   * // Create many ChatAdmins
   * const chatAdmin = await prisma.chatAdmin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChatAdminCreateManyArgs>(args?: Prisma.SelectSubset<T, ChatAdminCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ChatAdmins and returns the data saved in the database.
   * @param {ChatAdminCreateManyAndReturnArgs} args - Arguments to create many ChatAdmins.
   * @example
   * // Create many ChatAdmins
   * const chatAdmin = await prisma.chatAdmin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ChatAdmins and only return the `id`
   * const chatAdminWithIdOnly = await prisma.chatAdmin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChatAdminCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChatAdminCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ChatAdmin.
   * @param {ChatAdminDeleteArgs} args - Arguments to delete one ChatAdmin.
   * @example
   * // Delete one ChatAdmin
   * const ChatAdmin = await prisma.chatAdmin.delete({
   *   where: {
   *     // ... filter to delete one ChatAdmin
   *   }
   * })
   * 
   */
  delete<T extends ChatAdminDeleteArgs>(args: Prisma.SelectSubset<T, ChatAdminDeleteArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ChatAdmin.
   * @param {ChatAdminUpdateArgs} args - Arguments to update one ChatAdmin.
   * @example
   * // Update one ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChatAdminUpdateArgs>(args: Prisma.SelectSubset<T, ChatAdminUpdateArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ChatAdmins.
   * @param {ChatAdminDeleteManyArgs} args - Arguments to filter ChatAdmins to delete.
   * @example
   * // Delete a few ChatAdmins
   * const { count } = await prisma.chatAdmin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChatAdminDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChatAdminDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChatAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ChatAdmins
   * const chatAdmin = await prisma.chatAdmin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChatAdminUpdateManyArgs>(args: Prisma.SelectSubset<T, ChatAdminUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChatAdmins and returns the data updated in the database.
   * @param {ChatAdminUpdateManyAndReturnArgs} args - Arguments to update many ChatAdmins.
   * @example
   * // Update many ChatAdmins
   * const chatAdmin = await prisma.chatAdmin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ChatAdmins and only return the `id`
   * const chatAdminWithIdOnly = await prisma.chatAdmin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChatAdminUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChatAdminUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ChatAdmin.
   * @param {ChatAdminUpsertArgs} args - Arguments to update or create a ChatAdmin.
   * @example
   * // Update or create a ChatAdmin
   * const chatAdmin = await prisma.chatAdmin.upsert({
   *   create: {
   *     // ... data to create a ChatAdmin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ChatAdmin we want to update
   *   }
   * })
   */
  upsert<T extends ChatAdminUpsertArgs>(args: Prisma.SelectSubset<T, ChatAdminUpsertArgs<ExtArgs>>): Prisma.Prisma__ChatAdminClient<runtime.Types.Result.GetResult<Prisma.$ChatAdminPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ChatAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminCountArgs} args - Arguments to filter ChatAdmins to count.
   * @example
   * // Count the number of ChatAdmins
   * const count = await prisma.chatAdmin.count({
   *   where: {
   *     // ... the filter for the ChatAdmins we want to count
   *   }
   * })
  **/
  count<T extends ChatAdminCountArgs>(
    args?: Prisma.Subset<T, ChatAdminCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChatAdminCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ChatAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChatAdminAggregateArgs>(args: Prisma.Subset<T, ChatAdminAggregateArgs>): Prisma.PrismaPromise<GetChatAdminAggregateType<T>>

  /**
   * Group by ChatAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAdminGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChatAdminGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChatAdminGroupByArgs['orderBy'] }
      : { orderBy?: ChatAdminGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChatAdminGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChatAdminGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ChatAdmin model
 */
readonly fields: ChatAdminFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ChatAdmin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChatAdminClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ChatAdmin model
 */
export interface ChatAdminFieldRefs {
  readonly id: Prisma.FieldRef<"ChatAdmin", 'String'>
  readonly addedAt: Prisma.FieldRef<"ChatAdmin", 'DateTime'>
  readonly chatId: Prisma.FieldRef<"ChatAdmin", 'String'>
  readonly userId: Prisma.FieldRef<"ChatAdmin", 'String'>
}
    

// Custom InputTypes
/**
 * ChatAdmin findUnique
 */
export type ChatAdminFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter, which ChatAdmin to fetch.
   */
  where: Prisma.ChatAdminWhereUniqueInput
}

/**
 * ChatAdmin findUniqueOrThrow
 */
export type ChatAdminFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter, which ChatAdmin to fetch.
   */
  where: Prisma.ChatAdminWhereUniqueInput
}

/**
 * ChatAdmin findFirst
 */
export type ChatAdminFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter, which ChatAdmin to fetch.
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatAdmins to fetch.
   */
  orderBy?: Prisma.ChatAdminOrderByWithRelationInput | Prisma.ChatAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChatAdmins.
   */
  cursor?: Prisma.ChatAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChatAdmins.
   */
  distinct?: Prisma.ChatAdminScalarFieldEnum | Prisma.ChatAdminScalarFieldEnum[]
}

/**
 * ChatAdmin findFirstOrThrow
 */
export type ChatAdminFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter, which ChatAdmin to fetch.
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatAdmins to fetch.
   */
  orderBy?: Prisma.ChatAdminOrderByWithRelationInput | Prisma.ChatAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChatAdmins.
   */
  cursor?: Prisma.ChatAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChatAdmins.
   */
  distinct?: Prisma.ChatAdminScalarFieldEnum | Prisma.ChatAdminScalarFieldEnum[]
}

/**
 * ChatAdmin findMany
 */
export type ChatAdminFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter, which ChatAdmins to fetch.
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatAdmins to fetch.
   */
  orderBy?: Prisma.ChatAdminOrderByWithRelationInput | Prisma.ChatAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ChatAdmins.
   */
  cursor?: Prisma.ChatAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatAdmins.
   */
  skip?: number
  distinct?: Prisma.ChatAdminScalarFieldEnum | Prisma.ChatAdminScalarFieldEnum[]
}

/**
 * ChatAdmin create
 */
export type ChatAdminCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * The data needed to create a ChatAdmin.
   */
  data: Prisma.XOR<Prisma.ChatAdminCreateInput, Prisma.ChatAdminUncheckedCreateInput>
}

/**
 * ChatAdmin createMany
 */
export type ChatAdminCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ChatAdmins.
   */
  data: Prisma.ChatAdminCreateManyInput | Prisma.ChatAdminCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChatAdmin createManyAndReturn
 */
export type ChatAdminCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * The data used to create many ChatAdmins.
   */
  data: Prisma.ChatAdminCreateManyInput | Prisma.ChatAdminCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ChatAdmin update
 */
export type ChatAdminUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * The data needed to update a ChatAdmin.
   */
  data: Prisma.XOR<Prisma.ChatAdminUpdateInput, Prisma.ChatAdminUncheckedUpdateInput>
  /**
   * Choose, which ChatAdmin to update.
   */
  where: Prisma.ChatAdminWhereUniqueInput
}

/**
 * ChatAdmin updateMany
 */
export type ChatAdminUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ChatAdmins.
   */
  data: Prisma.XOR<Prisma.ChatAdminUpdateManyMutationInput, Prisma.ChatAdminUncheckedUpdateManyInput>
  /**
   * Filter which ChatAdmins to update
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * Limit how many ChatAdmins to update.
   */
  limit?: number
}

/**
 * ChatAdmin updateManyAndReturn
 */
export type ChatAdminUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * The data used to update ChatAdmins.
   */
  data: Prisma.XOR<Prisma.ChatAdminUpdateManyMutationInput, Prisma.ChatAdminUncheckedUpdateManyInput>
  /**
   * Filter which ChatAdmins to update
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * Limit how many ChatAdmins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ChatAdmin upsert
 */
export type ChatAdminUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * The filter to search for the ChatAdmin to update in case it exists.
   */
  where: Prisma.ChatAdminWhereUniqueInput
  /**
   * In case the ChatAdmin found by the `where` argument doesn't exist, create a new ChatAdmin with this data.
   */
  create: Prisma.XOR<Prisma.ChatAdminCreateInput, Prisma.ChatAdminUncheckedCreateInput>
  /**
   * In case the ChatAdmin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChatAdminUpdateInput, Prisma.ChatAdminUncheckedUpdateInput>
}

/**
 * ChatAdmin delete
 */
export type ChatAdminDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
  /**
   * Filter which ChatAdmin to delete.
   */
  where: Prisma.ChatAdminWhereUniqueInput
}

/**
 * ChatAdmin deleteMany
 */
export type ChatAdminDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChatAdmins to delete
   */
  where?: Prisma.ChatAdminWhereInput
  /**
   * Limit how many ChatAdmins to delete.
   */
  limit?: number
}

/**
 * ChatAdmin without action
 */
export type ChatAdminDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatAdmin
   */
  select?: Prisma.ChatAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatAdmin
   */
  omit?: Prisma.ChatAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatAdminInclude<ExtArgs> | null
}
