
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MutedChat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MutedChat
 * 
 */
export type MutedChatModel = runtime.Types.Result.DefaultSelection<Prisma.$MutedChatPayload>

export type AggregateMutedChat = {
  _count: MutedChatCountAggregateOutputType | null
  _min: MutedChatMinAggregateOutputType | null
  _max: MutedChatMaxAggregateOutputType | null
}

export type MutedChatMinAggregateOutputType = {
  id: string | null
  mutedUntil: Date | null
  mutedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type MutedChatMaxAggregateOutputType = {
  id: string | null
  mutedUntil: Date | null
  mutedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type MutedChatCountAggregateOutputType = {
  id: number
  mutedUntil: number
  mutedAt: number
  userId: number
  chatId: number
  _all: number
}


export type MutedChatMinAggregateInputType = {
  id?: true
  mutedUntil?: true
  mutedAt?: true
  userId?: true
  chatId?: true
}

export type MutedChatMaxAggregateInputType = {
  id?: true
  mutedUntil?: true
  mutedAt?: true
  userId?: true
  chatId?: true
}

export type MutedChatCountAggregateInputType = {
  id?: true
  mutedUntil?: true
  mutedAt?: true
  userId?: true
  chatId?: true
  _all?: true
}

export type MutedChatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MutedChat to aggregate.
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MutedChats to fetch.
   */
  orderBy?: Prisma.MutedChatOrderByWithRelationInput | Prisma.MutedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MutedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MutedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MutedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MutedChats
  **/
  _count?: true | MutedChatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MutedChatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MutedChatMaxAggregateInputType
}

export type GetMutedChatAggregateType<T extends MutedChatAggregateArgs> = {
      [P in keyof T & keyof AggregateMutedChat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMutedChat[P]>
    : Prisma.GetScalarType<T[P], AggregateMutedChat[P]>
}




export type MutedChatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MutedChatWhereInput
  orderBy?: Prisma.MutedChatOrderByWithAggregationInput | Prisma.MutedChatOrderByWithAggregationInput[]
  by: Prisma.MutedChatScalarFieldEnum[] | Prisma.MutedChatScalarFieldEnum
  having?: Prisma.MutedChatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MutedChatCountAggregateInputType | true
  _min?: MutedChatMinAggregateInputType
  _max?: MutedChatMaxAggregateInputType
}

export type MutedChatGroupByOutputType = {
  id: string
  mutedUntil: Date | null
  mutedAt: Date
  userId: string
  chatId: string
  _count: MutedChatCountAggregateOutputType | null
  _min: MutedChatMinAggregateOutputType | null
  _max: MutedChatMaxAggregateOutputType | null
}

type GetMutedChatGroupByPayload<T extends MutedChatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MutedChatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MutedChatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MutedChatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MutedChatGroupByOutputType[P]>
      }
    >
  >



export type MutedChatWhereInput = {
  AND?: Prisma.MutedChatWhereInput | Prisma.MutedChatWhereInput[]
  OR?: Prisma.MutedChatWhereInput[]
  NOT?: Prisma.MutedChatWhereInput | Prisma.MutedChatWhereInput[]
  id?: Prisma.StringFilter<"MutedChat"> | string
  mutedUntil?: Prisma.DateTimeNullableFilter<"MutedChat"> | Date | string | null
  mutedAt?: Prisma.DateTimeFilter<"MutedChat"> | Date | string
  userId?: Prisma.StringFilter<"MutedChat"> | string
  chatId?: Prisma.StringFilter<"MutedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}

export type MutedChatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mutedUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  mutedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  chat?: Prisma.ChatOrderByWithRelationInput
}

export type MutedChatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_chatId?: Prisma.MutedChatUserIdChatIdCompoundUniqueInput
  AND?: Prisma.MutedChatWhereInput | Prisma.MutedChatWhereInput[]
  OR?: Prisma.MutedChatWhereInput[]
  NOT?: Prisma.MutedChatWhereInput | Prisma.MutedChatWhereInput[]
  mutedUntil?: Prisma.DateTimeNullableFilter<"MutedChat"> | Date | string | null
  mutedAt?: Prisma.DateTimeFilter<"MutedChat"> | Date | string
  userId?: Prisma.StringFilter<"MutedChat"> | string
  chatId?: Prisma.StringFilter<"MutedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}, "id" | "userId_chatId">

export type MutedChatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mutedUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  mutedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  _count?: Prisma.MutedChatCountOrderByAggregateInput
  _max?: Prisma.MutedChatMaxOrderByAggregateInput
  _min?: Prisma.MutedChatMinOrderByAggregateInput
}

export type MutedChatScalarWhereWithAggregatesInput = {
  AND?: Prisma.MutedChatScalarWhereWithAggregatesInput | Prisma.MutedChatScalarWhereWithAggregatesInput[]
  OR?: Prisma.MutedChatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MutedChatScalarWhereWithAggregatesInput | Prisma.MutedChatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MutedChat"> | string
  mutedUntil?: Prisma.DateTimeNullableWithAggregatesFilter<"MutedChat"> | Date | string | null
  mutedAt?: Prisma.DateTimeWithAggregatesFilter<"MutedChat"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"MutedChat"> | string
  chatId?: Prisma.StringWithAggregatesFilter<"MutedChat"> | string
}

export type MutedChatCreateInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMutedChatsInput
  chat: Prisma.ChatCreateNestedOneWithoutMutedByInput
}

export type MutedChatUncheckedCreateInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  userId: string
  chatId: string
}

export type MutedChatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMutedChatsNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutMutedByNestedInput
}

export type MutedChatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MutedChatCreateManyInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  userId: string
  chatId: string
}

export type MutedChatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MutedChatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MutedChatListRelationFilter = {
  every?: Prisma.MutedChatWhereInput
  some?: Prisma.MutedChatWhereInput
  none?: Prisma.MutedChatWhereInput
}

export type MutedChatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MutedChatUserIdChatIdCompoundUniqueInput = {
  userId: string
  chatId: string
}

export type MutedChatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mutedUntil?: Prisma.SortOrder
  mutedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type MutedChatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mutedUntil?: Prisma.SortOrder
  mutedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type MutedChatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mutedUntil?: Prisma.SortOrder
  mutedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type MutedChatCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput> | Prisma.MutedChatCreateWithoutUserInput[] | Prisma.MutedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutUserInput | Prisma.MutedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MutedChatCreateManyUserInputEnvelope
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
}

export type MutedChatUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput> | Prisma.MutedChatCreateWithoutUserInput[] | Prisma.MutedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutUserInput | Prisma.MutedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MutedChatCreateManyUserInputEnvelope
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
}

export type MutedChatUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput> | Prisma.MutedChatCreateWithoutUserInput[] | Prisma.MutedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutUserInput | Prisma.MutedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MutedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.MutedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MutedChatCreateManyUserInputEnvelope
  set?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  disconnect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  delete?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  update?: Prisma.MutedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.MutedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MutedChatUpdateManyWithWhereWithoutUserInput | Prisma.MutedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
}

export type MutedChatUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput> | Prisma.MutedChatCreateWithoutUserInput[] | Prisma.MutedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutUserInput | Prisma.MutedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MutedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.MutedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MutedChatCreateManyUserInputEnvelope
  set?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  disconnect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  delete?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  update?: Prisma.MutedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.MutedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MutedChatUpdateManyWithWhereWithoutUserInput | Prisma.MutedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
}

export type MutedChatCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput> | Prisma.MutedChatCreateWithoutChatInput[] | Prisma.MutedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutChatInput | Prisma.MutedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.MutedChatCreateManyChatInputEnvelope
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
}

export type MutedChatUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput> | Prisma.MutedChatCreateWithoutChatInput[] | Prisma.MutedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutChatInput | Prisma.MutedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.MutedChatCreateManyChatInputEnvelope
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
}

export type MutedChatUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput> | Prisma.MutedChatCreateWithoutChatInput[] | Prisma.MutedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutChatInput | Prisma.MutedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.MutedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.MutedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.MutedChatCreateManyChatInputEnvelope
  set?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  disconnect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  delete?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  update?: Prisma.MutedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.MutedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.MutedChatUpdateManyWithWhereWithoutChatInput | Prisma.MutedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
}

export type MutedChatUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput> | Prisma.MutedChatCreateWithoutChatInput[] | Prisma.MutedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.MutedChatCreateOrConnectWithoutChatInput | Prisma.MutedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.MutedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.MutedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.MutedChatCreateManyChatInputEnvelope
  set?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  disconnect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  delete?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  connect?: Prisma.MutedChatWhereUniqueInput | Prisma.MutedChatWhereUniqueInput[]
  update?: Prisma.MutedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.MutedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.MutedChatUpdateManyWithWhereWithoutChatInput | Prisma.MutedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
}

export type MutedChatCreateWithoutUserInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutMutedByInput
}

export type MutedChatUncheckedCreateWithoutUserInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  chatId: string
}

export type MutedChatCreateOrConnectWithoutUserInput = {
  where: Prisma.MutedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput>
}

export type MutedChatCreateManyUserInputEnvelope = {
  data: Prisma.MutedChatCreateManyUserInput | Prisma.MutedChatCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MutedChatUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MutedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.MutedChatUpdateWithoutUserInput, Prisma.MutedChatUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MutedChatCreateWithoutUserInput, Prisma.MutedChatUncheckedCreateWithoutUserInput>
}

export type MutedChatUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MutedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.MutedChatUpdateWithoutUserInput, Prisma.MutedChatUncheckedUpdateWithoutUserInput>
}

export type MutedChatUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MutedChatScalarWhereInput
  data: Prisma.XOR<Prisma.MutedChatUpdateManyMutationInput, Prisma.MutedChatUncheckedUpdateManyWithoutUserInput>
}

export type MutedChatScalarWhereInput = {
  AND?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
  OR?: Prisma.MutedChatScalarWhereInput[]
  NOT?: Prisma.MutedChatScalarWhereInput | Prisma.MutedChatScalarWhereInput[]
  id?: Prisma.StringFilter<"MutedChat"> | string
  mutedUntil?: Prisma.DateTimeNullableFilter<"MutedChat"> | Date | string | null
  mutedAt?: Prisma.DateTimeFilter<"MutedChat"> | Date | string
  userId?: Prisma.StringFilter<"MutedChat"> | string
  chatId?: Prisma.StringFilter<"MutedChat"> | string
}

export type MutedChatCreateWithoutChatInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMutedChatsInput
}

export type MutedChatUncheckedCreateWithoutChatInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  userId: string
}

export type MutedChatCreateOrConnectWithoutChatInput = {
  where: Prisma.MutedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput>
}

export type MutedChatCreateManyChatInputEnvelope = {
  data: Prisma.MutedChatCreateManyChatInput | Prisma.MutedChatCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type MutedChatUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.MutedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.MutedChatUpdateWithoutChatInput, Prisma.MutedChatUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.MutedChatCreateWithoutChatInput, Prisma.MutedChatUncheckedCreateWithoutChatInput>
}

export type MutedChatUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.MutedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.MutedChatUpdateWithoutChatInput, Prisma.MutedChatUncheckedUpdateWithoutChatInput>
}

export type MutedChatUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.MutedChatScalarWhereInput
  data: Prisma.XOR<Prisma.MutedChatUpdateManyMutationInput, Prisma.MutedChatUncheckedUpdateManyWithoutChatInput>
}

export type MutedChatCreateManyUserInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  chatId: string
}

export type MutedChatUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutMutedByNestedInput
}

export type MutedChatUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MutedChatUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MutedChatCreateManyChatInput = {
  id?: string
  mutedUntil?: Date | string | null
  mutedAt?: Date | string
  userId: string
}

export type MutedChatUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMutedChatsNestedInput
}

export type MutedChatUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MutedChatUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mutedUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mutedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type MutedChatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mutedUntil?: boolean
  mutedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mutedChat"]>

export type MutedChatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mutedUntil?: boolean
  mutedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mutedChat"]>

export type MutedChatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mutedUntil?: boolean
  mutedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mutedChat"]>

export type MutedChatSelectScalar = {
  id?: boolean
  mutedUntil?: boolean
  mutedAt?: boolean
  userId?: boolean
  chatId?: boolean
}

export type MutedChatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mutedUntil" | "mutedAt" | "userId" | "chatId", ExtArgs["result"]["mutedChat"]>
export type MutedChatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type MutedChatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type MutedChatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}

export type $MutedChatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MutedChat"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    chat: Prisma.$ChatPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mutedUntil: Date | null
    mutedAt: Date
    userId: string
    chatId: string
  }, ExtArgs["result"]["mutedChat"]>
  composites: {}
}

export type MutedChatGetPayload<S extends boolean | null | undefined | MutedChatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MutedChatPayload, S>

export type MutedChatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MutedChatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MutedChatCountAggregateInputType | true
  }

export interface MutedChatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MutedChat'], meta: { name: 'MutedChat' } }
  /**
   * Find zero or one MutedChat that matches the filter.
   * @param {MutedChatFindUniqueArgs} args - Arguments to find a MutedChat
   * @example
   * // Get one MutedChat
   * const mutedChat = await prisma.mutedChat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MutedChatFindUniqueArgs>(args: Prisma.SelectSubset<T, MutedChatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MutedChat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MutedChatFindUniqueOrThrowArgs} args - Arguments to find a MutedChat
   * @example
   * // Get one MutedChat
   * const mutedChat = await prisma.mutedChat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MutedChatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MutedChatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MutedChat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatFindFirstArgs} args - Arguments to find a MutedChat
   * @example
   * // Get one MutedChat
   * const mutedChat = await prisma.mutedChat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MutedChatFindFirstArgs>(args?: Prisma.SelectSubset<T, MutedChatFindFirstArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MutedChat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatFindFirstOrThrowArgs} args - Arguments to find a MutedChat
   * @example
   * // Get one MutedChat
   * const mutedChat = await prisma.mutedChat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MutedChatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MutedChatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MutedChats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MutedChats
   * const mutedChats = await prisma.mutedChat.findMany()
   * 
   * // Get first 10 MutedChats
   * const mutedChats = await prisma.mutedChat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mutedChatWithIdOnly = await prisma.mutedChat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MutedChatFindManyArgs>(args?: Prisma.SelectSubset<T, MutedChatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MutedChat.
   * @param {MutedChatCreateArgs} args - Arguments to create a MutedChat.
   * @example
   * // Create one MutedChat
   * const MutedChat = await prisma.mutedChat.create({
   *   data: {
   *     // ... data to create a MutedChat
   *   }
   * })
   * 
   */
  create<T extends MutedChatCreateArgs>(args: Prisma.SelectSubset<T, MutedChatCreateArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MutedChats.
   * @param {MutedChatCreateManyArgs} args - Arguments to create many MutedChats.
   * @example
   * // Create many MutedChats
   * const mutedChat = await prisma.mutedChat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MutedChatCreateManyArgs>(args?: Prisma.SelectSubset<T, MutedChatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MutedChats and returns the data saved in the database.
   * @param {MutedChatCreateManyAndReturnArgs} args - Arguments to create many MutedChats.
   * @example
   * // Create many MutedChats
   * const mutedChat = await prisma.mutedChat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MutedChats and only return the `id`
   * const mutedChatWithIdOnly = await prisma.mutedChat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MutedChatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MutedChatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MutedChat.
   * @param {MutedChatDeleteArgs} args - Arguments to delete one MutedChat.
   * @example
   * // Delete one MutedChat
   * const MutedChat = await prisma.mutedChat.delete({
   *   where: {
   *     // ... filter to delete one MutedChat
   *   }
   * })
   * 
   */
  delete<T extends MutedChatDeleteArgs>(args: Prisma.SelectSubset<T, MutedChatDeleteArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MutedChat.
   * @param {MutedChatUpdateArgs} args - Arguments to update one MutedChat.
   * @example
   * // Update one MutedChat
   * const mutedChat = await prisma.mutedChat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MutedChatUpdateArgs>(args: Prisma.SelectSubset<T, MutedChatUpdateArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MutedChats.
   * @param {MutedChatDeleteManyArgs} args - Arguments to filter MutedChats to delete.
   * @example
   * // Delete a few MutedChats
   * const { count } = await prisma.mutedChat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MutedChatDeleteManyArgs>(args?: Prisma.SelectSubset<T, MutedChatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MutedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MutedChats
   * const mutedChat = await prisma.mutedChat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MutedChatUpdateManyArgs>(args: Prisma.SelectSubset<T, MutedChatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MutedChats and returns the data updated in the database.
   * @param {MutedChatUpdateManyAndReturnArgs} args - Arguments to update many MutedChats.
   * @example
   * // Update many MutedChats
   * const mutedChat = await prisma.mutedChat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MutedChats and only return the `id`
   * const mutedChatWithIdOnly = await prisma.mutedChat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MutedChatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MutedChatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MutedChat.
   * @param {MutedChatUpsertArgs} args - Arguments to update or create a MutedChat.
   * @example
   * // Update or create a MutedChat
   * const mutedChat = await prisma.mutedChat.upsert({
   *   create: {
   *     // ... data to create a MutedChat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MutedChat we want to update
   *   }
   * })
   */
  upsert<T extends MutedChatUpsertArgs>(args: Prisma.SelectSubset<T, MutedChatUpsertArgs<ExtArgs>>): Prisma.Prisma__MutedChatClient<runtime.Types.Result.GetResult<Prisma.$MutedChatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MutedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatCountArgs} args - Arguments to filter MutedChats to count.
   * @example
   * // Count the number of MutedChats
   * const count = await prisma.mutedChat.count({
   *   where: {
   *     // ... the filter for the MutedChats we want to count
   *   }
   * })
  **/
  count<T extends MutedChatCountArgs>(
    args?: Prisma.Subset<T, MutedChatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MutedChatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MutedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MutedChatAggregateArgs>(args: Prisma.Subset<T, MutedChatAggregateArgs>): Prisma.PrismaPromise<GetMutedChatAggregateType<T>>

  /**
   * Group by MutedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MutedChatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MutedChatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MutedChatGroupByArgs['orderBy'] }
      : { orderBy?: MutedChatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MutedChatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMutedChatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MutedChat model
 */
readonly fields: MutedChatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MutedChat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MutedChatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MutedChat model
 */
export interface MutedChatFieldRefs {
  readonly id: Prisma.FieldRef<"MutedChat", 'String'>
  readonly mutedUntil: Prisma.FieldRef<"MutedChat", 'DateTime'>
  readonly mutedAt: Prisma.FieldRef<"MutedChat", 'DateTime'>
  readonly userId: Prisma.FieldRef<"MutedChat", 'String'>
  readonly chatId: Prisma.FieldRef<"MutedChat", 'String'>
}
    

// Custom InputTypes
/**
 * MutedChat findUnique
 */
export type MutedChatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter, which MutedChat to fetch.
   */
  where: Prisma.MutedChatWhereUniqueInput
}

/**
 * MutedChat findUniqueOrThrow
 */
export type MutedChatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter, which MutedChat to fetch.
   */
  where: Prisma.MutedChatWhereUniqueInput
}

/**
 * MutedChat findFirst
 */
export type MutedChatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter, which MutedChat to fetch.
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MutedChats to fetch.
   */
  orderBy?: Prisma.MutedChatOrderByWithRelationInput | Prisma.MutedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MutedChats.
   */
  cursor?: Prisma.MutedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MutedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MutedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MutedChats.
   */
  distinct?: Prisma.MutedChatScalarFieldEnum | Prisma.MutedChatScalarFieldEnum[]
}

/**
 * MutedChat findFirstOrThrow
 */
export type MutedChatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter, which MutedChat to fetch.
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MutedChats to fetch.
   */
  orderBy?: Prisma.MutedChatOrderByWithRelationInput | Prisma.MutedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MutedChats.
   */
  cursor?: Prisma.MutedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MutedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MutedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MutedChats.
   */
  distinct?: Prisma.MutedChatScalarFieldEnum | Prisma.MutedChatScalarFieldEnum[]
}

/**
 * MutedChat findMany
 */
export type MutedChatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter, which MutedChats to fetch.
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MutedChats to fetch.
   */
  orderBy?: Prisma.MutedChatOrderByWithRelationInput | Prisma.MutedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MutedChats.
   */
  cursor?: Prisma.MutedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MutedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MutedChats.
   */
  skip?: number
  distinct?: Prisma.MutedChatScalarFieldEnum | Prisma.MutedChatScalarFieldEnum[]
}

/**
 * MutedChat create
 */
export type MutedChatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * The data needed to create a MutedChat.
   */
  data: Prisma.XOR<Prisma.MutedChatCreateInput, Prisma.MutedChatUncheckedCreateInput>
}

/**
 * MutedChat createMany
 */
export type MutedChatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MutedChats.
   */
  data: Prisma.MutedChatCreateManyInput | Prisma.MutedChatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MutedChat createManyAndReturn
 */
export type MutedChatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * The data used to create many MutedChats.
   */
  data: Prisma.MutedChatCreateManyInput | Prisma.MutedChatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MutedChat update
 */
export type MutedChatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * The data needed to update a MutedChat.
   */
  data: Prisma.XOR<Prisma.MutedChatUpdateInput, Prisma.MutedChatUncheckedUpdateInput>
  /**
   * Choose, which MutedChat to update.
   */
  where: Prisma.MutedChatWhereUniqueInput
}

/**
 * MutedChat updateMany
 */
export type MutedChatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MutedChats.
   */
  data: Prisma.XOR<Prisma.MutedChatUpdateManyMutationInput, Prisma.MutedChatUncheckedUpdateManyInput>
  /**
   * Filter which MutedChats to update
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * Limit how many MutedChats to update.
   */
  limit?: number
}

/**
 * MutedChat updateManyAndReturn
 */
export type MutedChatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * The data used to update MutedChats.
   */
  data: Prisma.XOR<Prisma.MutedChatUpdateManyMutationInput, Prisma.MutedChatUncheckedUpdateManyInput>
  /**
   * Filter which MutedChats to update
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * Limit how many MutedChats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MutedChat upsert
 */
export type MutedChatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * The filter to search for the MutedChat to update in case it exists.
   */
  where: Prisma.MutedChatWhereUniqueInput
  /**
   * In case the MutedChat found by the `where` argument doesn't exist, create a new MutedChat with this data.
   */
  create: Prisma.XOR<Prisma.MutedChatCreateInput, Prisma.MutedChatUncheckedCreateInput>
  /**
   * In case the MutedChat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MutedChatUpdateInput, Prisma.MutedChatUncheckedUpdateInput>
}

/**
 * MutedChat delete
 */
export type MutedChatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
  /**
   * Filter which MutedChat to delete.
   */
  where: Prisma.MutedChatWhereUniqueInput
}

/**
 * MutedChat deleteMany
 */
export type MutedChatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MutedChats to delete
   */
  where?: Prisma.MutedChatWhereInput
  /**
   * Limit how many MutedChats to delete.
   */
  limit?: number
}

/**
 * MutedChat without action
 */
export type MutedChatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MutedChat
   */
  select?: Prisma.MutedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MutedChat
   */
  omit?: Prisma.MutedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MutedChatInclude<ExtArgs> | null
}
