
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PinnedChat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PinnedChat
 * 
 */
export type PinnedChatModel = runtime.Types.Result.DefaultSelection<Prisma.$PinnedChatPayload>

export type AggregatePinnedChat = {
  _count: PinnedChatCountAggregateOutputType | null
  _min: PinnedChatMinAggregateOutputType | null
  _max: PinnedChatMaxAggregateOutputType | null
}

export type PinnedChatMinAggregateOutputType = {
  id: string | null
  pinnedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type PinnedChatMaxAggregateOutputType = {
  id: string | null
  pinnedAt: Date | null
  userId: string | null
  chatId: string | null
}

export type PinnedChatCountAggregateOutputType = {
  id: number
  pinnedAt: number
  userId: number
  chatId: number
  _all: number
}


export type PinnedChatMinAggregateInputType = {
  id?: true
  pinnedAt?: true
  userId?: true
  chatId?: true
}

export type PinnedChatMaxAggregateInputType = {
  id?: true
  pinnedAt?: true
  userId?: true
  chatId?: true
}

export type PinnedChatCountAggregateInputType = {
  id?: true
  pinnedAt?: true
  userId?: true
  chatId?: true
  _all?: true
}

export type PinnedChatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinnedChat to aggregate.
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinnedChats to fetch.
   */
  orderBy?: Prisma.PinnedChatOrderByWithRelationInput | Prisma.PinnedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PinnedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinnedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinnedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PinnedChats
  **/
  _count?: true | PinnedChatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PinnedChatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PinnedChatMaxAggregateInputType
}

export type GetPinnedChatAggregateType<T extends PinnedChatAggregateArgs> = {
      [P in keyof T & keyof AggregatePinnedChat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePinnedChat[P]>
    : Prisma.GetScalarType<T[P], AggregatePinnedChat[P]>
}




export type PinnedChatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PinnedChatWhereInput
  orderBy?: Prisma.PinnedChatOrderByWithAggregationInput | Prisma.PinnedChatOrderByWithAggregationInput[]
  by: Prisma.PinnedChatScalarFieldEnum[] | Prisma.PinnedChatScalarFieldEnum
  having?: Prisma.PinnedChatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PinnedChatCountAggregateInputType | true
  _min?: PinnedChatMinAggregateInputType
  _max?: PinnedChatMaxAggregateInputType
}

export type PinnedChatGroupByOutputType = {
  id: string
  pinnedAt: Date
  userId: string
  chatId: string
  _count: PinnedChatCountAggregateOutputType | null
  _min: PinnedChatMinAggregateOutputType | null
  _max: PinnedChatMaxAggregateOutputType | null
}

type GetPinnedChatGroupByPayload<T extends PinnedChatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PinnedChatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PinnedChatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PinnedChatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PinnedChatGroupByOutputType[P]>
      }
    >
  >



export type PinnedChatWhereInput = {
  AND?: Prisma.PinnedChatWhereInput | Prisma.PinnedChatWhereInput[]
  OR?: Prisma.PinnedChatWhereInput[]
  NOT?: Prisma.PinnedChatWhereInput | Prisma.PinnedChatWhereInput[]
  id?: Prisma.StringFilter<"PinnedChat"> | string
  pinnedAt?: Prisma.DateTimeFilter<"PinnedChat"> | Date | string
  userId?: Prisma.StringFilter<"PinnedChat"> | string
  chatId?: Prisma.StringFilter<"PinnedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}

export type PinnedChatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pinnedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  chat?: Prisma.ChatOrderByWithRelationInput
}

export type PinnedChatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_chatId?: Prisma.PinnedChatUserIdChatIdCompoundUniqueInput
  AND?: Prisma.PinnedChatWhereInput | Prisma.PinnedChatWhereInput[]
  OR?: Prisma.PinnedChatWhereInput[]
  NOT?: Prisma.PinnedChatWhereInput | Prisma.PinnedChatWhereInput[]
  pinnedAt?: Prisma.DateTimeFilter<"PinnedChat"> | Date | string
  userId?: Prisma.StringFilter<"PinnedChat"> | string
  chatId?: Prisma.StringFilter<"PinnedChat"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
}, "id" | "userId_chatId">

export type PinnedChatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pinnedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  _count?: Prisma.PinnedChatCountOrderByAggregateInput
  _max?: Prisma.PinnedChatMaxOrderByAggregateInput
  _min?: Prisma.PinnedChatMinOrderByAggregateInput
}

export type PinnedChatScalarWhereWithAggregatesInput = {
  AND?: Prisma.PinnedChatScalarWhereWithAggregatesInput | Prisma.PinnedChatScalarWhereWithAggregatesInput[]
  OR?: Prisma.PinnedChatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PinnedChatScalarWhereWithAggregatesInput | Prisma.PinnedChatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PinnedChat"> | string
  pinnedAt?: Prisma.DateTimeWithAggregatesFilter<"PinnedChat"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"PinnedChat"> | string
  chatId?: Prisma.StringWithAggregatesFilter<"PinnedChat"> | string
}

export type PinnedChatCreateInput = {
  id?: string
  pinnedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPinnedChatsInput
  chat: Prisma.ChatCreateNestedOneWithoutPinnedChatsInput
}

export type PinnedChatUncheckedCreateInput = {
  id?: string
  pinnedAt?: Date | string
  userId: string
  chatId: string
}

export type PinnedChatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPinnedChatsNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutPinnedChatsNestedInput
}

export type PinnedChatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PinnedChatCreateManyInput = {
  id?: string
  pinnedAt?: Date | string
  userId: string
  chatId: string
}

export type PinnedChatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PinnedChatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PinnedChatListRelationFilter = {
  every?: Prisma.PinnedChatWhereInput
  some?: Prisma.PinnedChatWhereInput
  none?: Prisma.PinnedChatWhereInput
}

export type PinnedChatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PinnedChatUserIdChatIdCompoundUniqueInput = {
  userId: string
  chatId: string
}

export type PinnedChatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pinnedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type PinnedChatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pinnedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type PinnedChatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pinnedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
}

export type PinnedChatCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput> | Prisma.PinnedChatCreateWithoutUserInput[] | Prisma.PinnedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutUserInput | Prisma.PinnedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PinnedChatCreateManyUserInputEnvelope
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
}

export type PinnedChatUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput> | Prisma.PinnedChatCreateWithoutUserInput[] | Prisma.PinnedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutUserInput | Prisma.PinnedChatCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PinnedChatCreateManyUserInputEnvelope
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
}

export type PinnedChatUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput> | Prisma.PinnedChatCreateWithoutUserInput[] | Prisma.PinnedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutUserInput | Prisma.PinnedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PinnedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.PinnedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PinnedChatCreateManyUserInputEnvelope
  set?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  disconnect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  delete?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  update?: Prisma.PinnedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.PinnedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PinnedChatUpdateManyWithWhereWithoutUserInput | Prisma.PinnedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
}

export type PinnedChatUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput> | Prisma.PinnedChatCreateWithoutUserInput[] | Prisma.PinnedChatUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutUserInput | Prisma.PinnedChatCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PinnedChatUpsertWithWhereUniqueWithoutUserInput | Prisma.PinnedChatUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PinnedChatCreateManyUserInputEnvelope
  set?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  disconnect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  delete?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  update?: Prisma.PinnedChatUpdateWithWhereUniqueWithoutUserInput | Prisma.PinnedChatUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PinnedChatUpdateManyWithWhereWithoutUserInput | Prisma.PinnedChatUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
}

export type PinnedChatCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput> | Prisma.PinnedChatCreateWithoutChatInput[] | Prisma.PinnedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutChatInput | Prisma.PinnedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.PinnedChatCreateManyChatInputEnvelope
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
}

export type PinnedChatUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput> | Prisma.PinnedChatCreateWithoutChatInput[] | Prisma.PinnedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutChatInput | Prisma.PinnedChatCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.PinnedChatCreateManyChatInputEnvelope
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
}

export type PinnedChatUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput> | Prisma.PinnedChatCreateWithoutChatInput[] | Prisma.PinnedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutChatInput | Prisma.PinnedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.PinnedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.PinnedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.PinnedChatCreateManyChatInputEnvelope
  set?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  disconnect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  delete?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  update?: Prisma.PinnedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.PinnedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.PinnedChatUpdateManyWithWhereWithoutChatInput | Prisma.PinnedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
}

export type PinnedChatUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput> | Prisma.PinnedChatCreateWithoutChatInput[] | Prisma.PinnedChatUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.PinnedChatCreateOrConnectWithoutChatInput | Prisma.PinnedChatCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.PinnedChatUpsertWithWhereUniqueWithoutChatInput | Prisma.PinnedChatUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.PinnedChatCreateManyChatInputEnvelope
  set?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  disconnect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  delete?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  connect?: Prisma.PinnedChatWhereUniqueInput | Prisma.PinnedChatWhereUniqueInput[]
  update?: Prisma.PinnedChatUpdateWithWhereUniqueWithoutChatInput | Prisma.PinnedChatUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.PinnedChatUpdateManyWithWhereWithoutChatInput | Prisma.PinnedChatUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
}

export type PinnedChatCreateWithoutUserInput = {
  id?: string
  pinnedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutPinnedChatsInput
}

export type PinnedChatUncheckedCreateWithoutUserInput = {
  id?: string
  pinnedAt?: Date | string
  chatId: string
}

export type PinnedChatCreateOrConnectWithoutUserInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput>
}

export type PinnedChatCreateManyUserInputEnvelope = {
  data: Prisma.PinnedChatCreateManyUserInput | Prisma.PinnedChatCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PinnedChatUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.PinnedChatUpdateWithoutUserInput, Prisma.PinnedChatUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PinnedChatCreateWithoutUserInput, Prisma.PinnedChatUncheckedCreateWithoutUserInput>
}

export type PinnedChatUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.PinnedChatUpdateWithoutUserInput, Prisma.PinnedChatUncheckedUpdateWithoutUserInput>
}

export type PinnedChatUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PinnedChatScalarWhereInput
  data: Prisma.XOR<Prisma.PinnedChatUpdateManyMutationInput, Prisma.PinnedChatUncheckedUpdateManyWithoutUserInput>
}

export type PinnedChatScalarWhereInput = {
  AND?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
  OR?: Prisma.PinnedChatScalarWhereInput[]
  NOT?: Prisma.PinnedChatScalarWhereInput | Prisma.PinnedChatScalarWhereInput[]
  id?: Prisma.StringFilter<"PinnedChat"> | string
  pinnedAt?: Prisma.DateTimeFilter<"PinnedChat"> | Date | string
  userId?: Prisma.StringFilter<"PinnedChat"> | string
  chatId?: Prisma.StringFilter<"PinnedChat"> | string
}

export type PinnedChatCreateWithoutChatInput = {
  id?: string
  pinnedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPinnedChatsInput
}

export type PinnedChatUncheckedCreateWithoutChatInput = {
  id?: string
  pinnedAt?: Date | string
  userId: string
}

export type PinnedChatCreateOrConnectWithoutChatInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  create: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput>
}

export type PinnedChatCreateManyChatInputEnvelope = {
  data: Prisma.PinnedChatCreateManyChatInput | Prisma.PinnedChatCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type PinnedChatUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  update: Prisma.XOR<Prisma.PinnedChatUpdateWithoutChatInput, Prisma.PinnedChatUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.PinnedChatCreateWithoutChatInput, Prisma.PinnedChatUncheckedCreateWithoutChatInput>
}

export type PinnedChatUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.PinnedChatWhereUniqueInput
  data: Prisma.XOR<Prisma.PinnedChatUpdateWithoutChatInput, Prisma.PinnedChatUncheckedUpdateWithoutChatInput>
}

export type PinnedChatUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.PinnedChatScalarWhereInput
  data: Prisma.XOR<Prisma.PinnedChatUpdateManyMutationInput, Prisma.PinnedChatUncheckedUpdateManyWithoutChatInput>
}

export type PinnedChatCreateManyUserInput = {
  id?: string
  pinnedAt?: Date | string
  chatId: string
}

export type PinnedChatUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutPinnedChatsNestedInput
}

export type PinnedChatUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PinnedChatUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PinnedChatCreateManyChatInput = {
  id?: string
  pinnedAt?: Date | string
  userId: string
}

export type PinnedChatUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPinnedChatsNestedInput
}

export type PinnedChatUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PinnedChatUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pinnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PinnedChatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pinnedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinnedChat"]>

export type PinnedChatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pinnedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinnedChat"]>

export type PinnedChatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pinnedAt?: boolean
  userId?: boolean
  chatId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinnedChat"]>

export type PinnedChatSelectScalar = {
  id?: boolean
  pinnedAt?: boolean
  userId?: boolean
  chatId?: boolean
}

export type PinnedChatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pinnedAt" | "userId" | "chatId", ExtArgs["result"]["pinnedChat"]>
export type PinnedChatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type PinnedChatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type PinnedChatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}

export type $PinnedChatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PinnedChat"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    chat: Prisma.$ChatPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pinnedAt: Date
    userId: string
    chatId: string
  }, ExtArgs["result"]["pinnedChat"]>
  composites: {}
}

export type PinnedChatGetPayload<S extends boolean | null | undefined | PinnedChatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload, S>

export type PinnedChatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PinnedChatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PinnedChatCountAggregateInputType | true
  }

export interface PinnedChatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PinnedChat'], meta: { name: 'PinnedChat' } }
  /**
   * Find zero or one PinnedChat that matches the filter.
   * @param {PinnedChatFindUniqueArgs} args - Arguments to find a PinnedChat
   * @example
   * // Get one PinnedChat
   * const pinnedChat = await prisma.pinnedChat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PinnedChatFindUniqueArgs>(args: Prisma.SelectSubset<T, PinnedChatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PinnedChat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PinnedChatFindUniqueOrThrowArgs} args - Arguments to find a PinnedChat
   * @example
   * // Get one PinnedChat
   * const pinnedChat = await prisma.pinnedChat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PinnedChatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PinnedChatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinnedChat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatFindFirstArgs} args - Arguments to find a PinnedChat
   * @example
   * // Get one PinnedChat
   * const pinnedChat = await prisma.pinnedChat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PinnedChatFindFirstArgs>(args?: Prisma.SelectSubset<T, PinnedChatFindFirstArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinnedChat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatFindFirstOrThrowArgs} args - Arguments to find a PinnedChat
   * @example
   * // Get one PinnedChat
   * const pinnedChat = await prisma.pinnedChat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PinnedChatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PinnedChatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PinnedChats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PinnedChats
   * const pinnedChats = await prisma.pinnedChat.findMany()
   * 
   * // Get first 10 PinnedChats
   * const pinnedChats = await prisma.pinnedChat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pinnedChatWithIdOnly = await prisma.pinnedChat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PinnedChatFindManyArgs>(args?: Prisma.SelectSubset<T, PinnedChatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PinnedChat.
   * @param {PinnedChatCreateArgs} args - Arguments to create a PinnedChat.
   * @example
   * // Create one PinnedChat
   * const PinnedChat = await prisma.pinnedChat.create({
   *   data: {
   *     // ... data to create a PinnedChat
   *   }
   * })
   * 
   */
  create<T extends PinnedChatCreateArgs>(args: Prisma.SelectSubset<T, PinnedChatCreateArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PinnedChats.
   * @param {PinnedChatCreateManyArgs} args - Arguments to create many PinnedChats.
   * @example
   * // Create many PinnedChats
   * const pinnedChat = await prisma.pinnedChat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PinnedChatCreateManyArgs>(args?: Prisma.SelectSubset<T, PinnedChatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PinnedChats and returns the data saved in the database.
   * @param {PinnedChatCreateManyAndReturnArgs} args - Arguments to create many PinnedChats.
   * @example
   * // Create many PinnedChats
   * const pinnedChat = await prisma.pinnedChat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PinnedChats and only return the `id`
   * const pinnedChatWithIdOnly = await prisma.pinnedChat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PinnedChatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PinnedChatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PinnedChat.
   * @param {PinnedChatDeleteArgs} args - Arguments to delete one PinnedChat.
   * @example
   * // Delete one PinnedChat
   * const PinnedChat = await prisma.pinnedChat.delete({
   *   where: {
   *     // ... filter to delete one PinnedChat
   *   }
   * })
   * 
   */
  delete<T extends PinnedChatDeleteArgs>(args: Prisma.SelectSubset<T, PinnedChatDeleteArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PinnedChat.
   * @param {PinnedChatUpdateArgs} args - Arguments to update one PinnedChat.
   * @example
   * // Update one PinnedChat
   * const pinnedChat = await prisma.pinnedChat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PinnedChatUpdateArgs>(args: Prisma.SelectSubset<T, PinnedChatUpdateArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PinnedChats.
   * @param {PinnedChatDeleteManyArgs} args - Arguments to filter PinnedChats to delete.
   * @example
   * // Delete a few PinnedChats
   * const { count } = await prisma.pinnedChat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PinnedChatDeleteManyArgs>(args?: Prisma.SelectSubset<T, PinnedChatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinnedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PinnedChats
   * const pinnedChat = await prisma.pinnedChat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PinnedChatUpdateManyArgs>(args: Prisma.SelectSubset<T, PinnedChatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinnedChats and returns the data updated in the database.
   * @param {PinnedChatUpdateManyAndReturnArgs} args - Arguments to update many PinnedChats.
   * @example
   * // Update many PinnedChats
   * const pinnedChat = await prisma.pinnedChat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PinnedChats and only return the `id`
   * const pinnedChatWithIdOnly = await prisma.pinnedChat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PinnedChatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PinnedChatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PinnedChat.
   * @param {PinnedChatUpsertArgs} args - Arguments to update or create a PinnedChat.
   * @example
   * // Update or create a PinnedChat
   * const pinnedChat = await prisma.pinnedChat.upsert({
   *   create: {
   *     // ... data to create a PinnedChat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PinnedChat we want to update
   *   }
   * })
   */
  upsert<T extends PinnedChatUpsertArgs>(args: Prisma.SelectSubset<T, PinnedChatUpsertArgs<ExtArgs>>): Prisma.Prisma__PinnedChatClient<runtime.Types.Result.GetResult<Prisma.$PinnedChatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PinnedChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatCountArgs} args - Arguments to filter PinnedChats to count.
   * @example
   * // Count the number of PinnedChats
   * const count = await prisma.pinnedChat.count({
   *   where: {
   *     // ... the filter for the PinnedChats we want to count
   *   }
   * })
  **/
  count<T extends PinnedChatCountArgs>(
    args?: Prisma.Subset<T, PinnedChatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PinnedChatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PinnedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PinnedChatAggregateArgs>(args: Prisma.Subset<T, PinnedChatAggregateArgs>): Prisma.PrismaPromise<GetPinnedChatAggregateType<T>>

  /**
   * Group by PinnedChat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinnedChatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PinnedChatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PinnedChatGroupByArgs['orderBy'] }
      : { orderBy?: PinnedChatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PinnedChatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPinnedChatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PinnedChat model
 */
readonly fields: PinnedChatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PinnedChat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PinnedChatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PinnedChat model
 */
export interface PinnedChatFieldRefs {
  readonly id: Prisma.FieldRef<"PinnedChat", 'String'>
  readonly pinnedAt: Prisma.FieldRef<"PinnedChat", 'DateTime'>
  readonly userId: Prisma.FieldRef<"PinnedChat", 'String'>
  readonly chatId: Prisma.FieldRef<"PinnedChat", 'String'>
}
    

// Custom InputTypes
/**
 * PinnedChat findUnique
 */
export type PinnedChatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter, which PinnedChat to fetch.
   */
  where: Prisma.PinnedChatWhereUniqueInput
}

/**
 * PinnedChat findUniqueOrThrow
 */
export type PinnedChatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter, which PinnedChat to fetch.
   */
  where: Prisma.PinnedChatWhereUniqueInput
}

/**
 * PinnedChat findFirst
 */
export type PinnedChatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter, which PinnedChat to fetch.
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinnedChats to fetch.
   */
  orderBy?: Prisma.PinnedChatOrderByWithRelationInput | Prisma.PinnedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinnedChats.
   */
  cursor?: Prisma.PinnedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinnedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinnedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinnedChats.
   */
  distinct?: Prisma.PinnedChatScalarFieldEnum | Prisma.PinnedChatScalarFieldEnum[]
}

/**
 * PinnedChat findFirstOrThrow
 */
export type PinnedChatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter, which PinnedChat to fetch.
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinnedChats to fetch.
   */
  orderBy?: Prisma.PinnedChatOrderByWithRelationInput | Prisma.PinnedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinnedChats.
   */
  cursor?: Prisma.PinnedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinnedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinnedChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinnedChats.
   */
  distinct?: Prisma.PinnedChatScalarFieldEnum | Prisma.PinnedChatScalarFieldEnum[]
}

/**
 * PinnedChat findMany
 */
export type PinnedChatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter, which PinnedChats to fetch.
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinnedChats to fetch.
   */
  orderBy?: Prisma.PinnedChatOrderByWithRelationInput | Prisma.PinnedChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PinnedChats.
   */
  cursor?: Prisma.PinnedChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinnedChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinnedChats.
   */
  skip?: number
  distinct?: Prisma.PinnedChatScalarFieldEnum | Prisma.PinnedChatScalarFieldEnum[]
}

/**
 * PinnedChat create
 */
export type PinnedChatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * The data needed to create a PinnedChat.
   */
  data: Prisma.XOR<Prisma.PinnedChatCreateInput, Prisma.PinnedChatUncheckedCreateInput>
}

/**
 * PinnedChat createMany
 */
export type PinnedChatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PinnedChats.
   */
  data: Prisma.PinnedChatCreateManyInput | Prisma.PinnedChatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PinnedChat createManyAndReturn
 */
export type PinnedChatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * The data used to create many PinnedChats.
   */
  data: Prisma.PinnedChatCreateManyInput | Prisma.PinnedChatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PinnedChat update
 */
export type PinnedChatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * The data needed to update a PinnedChat.
   */
  data: Prisma.XOR<Prisma.PinnedChatUpdateInput, Prisma.PinnedChatUncheckedUpdateInput>
  /**
   * Choose, which PinnedChat to update.
   */
  where: Prisma.PinnedChatWhereUniqueInput
}

/**
 * PinnedChat updateMany
 */
export type PinnedChatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PinnedChats.
   */
  data: Prisma.XOR<Prisma.PinnedChatUpdateManyMutationInput, Prisma.PinnedChatUncheckedUpdateManyInput>
  /**
   * Filter which PinnedChats to update
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * Limit how many PinnedChats to update.
   */
  limit?: number
}

/**
 * PinnedChat updateManyAndReturn
 */
export type PinnedChatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * The data used to update PinnedChats.
   */
  data: Prisma.XOR<Prisma.PinnedChatUpdateManyMutationInput, Prisma.PinnedChatUncheckedUpdateManyInput>
  /**
   * Filter which PinnedChats to update
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * Limit how many PinnedChats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PinnedChat upsert
 */
export type PinnedChatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * The filter to search for the PinnedChat to update in case it exists.
   */
  where: Prisma.PinnedChatWhereUniqueInput
  /**
   * In case the PinnedChat found by the `where` argument doesn't exist, create a new PinnedChat with this data.
   */
  create: Prisma.XOR<Prisma.PinnedChatCreateInput, Prisma.PinnedChatUncheckedCreateInput>
  /**
   * In case the PinnedChat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PinnedChatUpdateInput, Prisma.PinnedChatUncheckedUpdateInput>
}

/**
 * PinnedChat delete
 */
export type PinnedChatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
  /**
   * Filter which PinnedChat to delete.
   */
  where: Prisma.PinnedChatWhereUniqueInput
}

/**
 * PinnedChat deleteMany
 */
export type PinnedChatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinnedChats to delete
   */
  where?: Prisma.PinnedChatWhereInput
  /**
   * Limit how many PinnedChats to delete.
   */
  limit?: number
}

/**
 * PinnedChat without action
 */
export type PinnedChatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinnedChat
   */
  select?: Prisma.PinnedChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinnedChat
   */
  omit?: Prisma.PinnedChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinnedChatInclude<ExtArgs> | null
}
