
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumEnumUserStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserStatus | Prisma.EnumEnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel> | $Enums.EnumUserStatus
}

export type EnumEnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserRole | Prisma.EnumEnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel> | $Enums.EnumUserRole
}

export type EnumEnumUserVisibilityFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserVisibility | Prisma.EnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel> | $Enums.EnumUserVisibility
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumEnumUserStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserStatus | Prisma.EnumEnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel>
}

export type EnumEnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserRole | Prisma.EnumEnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel>
}

export type EnumEnumUserVisibilityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserVisibility | Prisma.EnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserVisibilityWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserVisibility
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumEnumFriendshipStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumFriendshipStatus | Prisma.EnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel> | $Enums.EnumFriendshipStatus
}

export type EnumEnumFriendshipStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumFriendshipStatus | Prisma.EnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumFriendshipStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumFriendshipStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel>
}

export type EnumEnumChatTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumChatType | Prisma.EnumEnumChatTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel> | $Enums.EnumChatType
}

export type EnumEnumChatTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumChatType | Prisma.EnumEnumChatTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumChatTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumChatType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel>
}

export type EnumEnumMemberRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMemberRole | Prisma.EnumEnumMemberRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel> | $Enums.EnumMemberRole
}

export type EnumEnumMemberRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMemberRole | Prisma.EnumEnumMemberRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMemberRoleWithAggregatesFilter<$PrismaModel> | $Enums.EnumMemberRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel>
}

export type EnumEnumMessageStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMessageStatus | Prisma.EnumEnumMessageStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel> | $Enums.EnumMessageStatus
}

export type EnumEnumMessageStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMessageStatus | Prisma.EnumEnumMessageStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMessageStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumMessageStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel>
}

export type EnumEnumMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMediaType | Prisma.EnumEnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel> | $Enums.EnumMediaType
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumEnumMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMediaType | Prisma.EnumEnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumMediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumEnumTokenTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumTokenType | Prisma.EnumEnumTokenTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel> | $Enums.EnumTokenType
}

export type EnumEnumTokenTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumTokenType | Prisma.EnumEnumTokenTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumTokenTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumTokenType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumEnumUserStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserStatus | Prisma.EnumEnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel> | $Enums.EnumUserStatus
}

export type NestedEnumEnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserRole | Prisma.EnumEnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel> | $Enums.EnumUserRole
}

export type NestedEnumEnumUserVisibilityFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserVisibility | Prisma.EnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel> | $Enums.EnumUserVisibility
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumEnumUserStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserStatus | Prisma.EnumEnumUserStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserStatus[] | Prisma.ListEnumEnumUserStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserStatusFilter<$PrismaModel>
}

export type NestedEnumEnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserRole | Prisma.EnumEnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserRole[] | Prisma.ListEnumEnumUserRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserRoleFilter<$PrismaModel>
}

export type NestedEnumEnumUserVisibilityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumUserVisibility | Prisma.EnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  in?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumUserVisibility[] | Prisma.ListEnumEnumUserVisibilityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumUserVisibilityWithAggregatesFilter<$PrismaModel> | $Enums.EnumUserVisibility
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumUserVisibilityFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumEnumFriendshipStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumFriendshipStatus | Prisma.EnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel> | $Enums.EnumFriendshipStatus
}

export type NestedEnumEnumFriendshipStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumFriendshipStatus | Prisma.EnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumFriendshipStatus[] | Prisma.ListEnumEnumFriendshipStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumFriendshipStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumFriendshipStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumFriendshipStatusFilter<$PrismaModel>
}

export type NestedEnumEnumChatTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumChatType | Prisma.EnumEnumChatTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel> | $Enums.EnumChatType
}

export type NestedEnumEnumChatTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumChatType | Prisma.EnumEnumChatTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumChatType[] | Prisma.ListEnumEnumChatTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumChatTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumChatType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumChatTypeFilter<$PrismaModel>
}

export type NestedEnumEnumMemberRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMemberRole | Prisma.EnumEnumMemberRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel> | $Enums.EnumMemberRole
}

export type NestedEnumEnumMemberRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMemberRole | Prisma.EnumEnumMemberRoleFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMemberRole[] | Prisma.ListEnumEnumMemberRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMemberRoleWithAggregatesFilter<$PrismaModel> | $Enums.EnumMemberRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMemberRoleFilter<$PrismaModel>
}

export type NestedEnumEnumMessageStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMessageStatus | Prisma.EnumEnumMessageStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel> | $Enums.EnumMessageStatus
}

export type NestedEnumEnumMessageStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMessageStatus | Prisma.EnumEnumMessageStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMessageStatus[] | Prisma.ListEnumEnumMessageStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMessageStatusWithAggregatesFilter<$PrismaModel> | $Enums.EnumMessageStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMessageStatusFilter<$PrismaModel>
}

export type NestedEnumEnumMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMediaType | Prisma.EnumEnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel> | $Enums.EnumMediaType
}

export type NestedEnumEnumMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumMediaType | Prisma.EnumEnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumMediaType[] | Prisma.ListEnumEnumMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumMediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumMediaTypeFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumEnumTokenTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumTokenType | Prisma.EnumEnumTokenTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel> | $Enums.EnumTokenType
}

export type NestedEnumEnumTokenTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EnumTokenType | Prisma.EnumEnumTokenTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EnumTokenType[] | Prisma.ListEnumEnumTokenTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnumTokenTypeWithAggregatesFilter<$PrismaModel> | $Enums.EnumTokenType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnumTokenTypeFilter<$PrismaModel>
}


