
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const EnumTokenType = {
  VERIFICATION: 'VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET'
} as const

export type EnumTokenType = (typeof EnumTokenType)[keyof typeof EnumTokenType]


export const EnumUserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type EnumUserRole = (typeof EnumUserRole)[keyof typeof EnumUserRole]


export const EnumUserStatus = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE'
} as const

export type EnumUserStatus = (typeof EnumUserStatus)[keyof typeof EnumUserStatus]


export const EnumUserVisibility = {
  VISIBLE: 'VISIBLE',
  INVISIBLE: 'INVISIBLE'
} as const

export type EnumUserVisibility = (typeof EnumUserVisibility)[keyof typeof EnumUserVisibility]


export const EnumChatType = {
  DIRECT: 'DIRECT',
  GROUP: 'GROUP',
  CHANNEL: 'CHANNEL'
} as const

export type EnumChatType = (typeof EnumChatType)[keyof typeof EnumChatType]


export const EnumMemberRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type EnumMemberRole = (typeof EnumMemberRole)[keyof typeof EnumMemberRole]


export const EnumMessageStatus = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  FAILED: 'FAILED',
  DELETED: 'DELETED'
} as const

export type EnumMessageStatus = (typeof EnumMessageStatus)[keyof typeof EnumMessageStatus]


export const EnumMediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  DOCUMENT: 'DOCUMENT',
  VOICE: 'VOICE',
  GIF: 'GIF'
} as const

export type EnumMediaType = (typeof EnumMediaType)[keyof typeof EnumMediaType]


export const EnumFriendshipStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  BLOCKED: 'BLOCKED'
} as const

export type EnumFriendshipStatus = (typeof EnumFriendshipStatus)[keyof typeof EnumFriendshipStatus]
